### DISCUSSION TITLE
Is it possible to define recipe options in maven config or per command line property

### DISCUSSION THREAD

**Discussion by aabeling** [openrewrite/rewrite#1637] [Q&A] [answered]
Hi,

the example https://docs.openrewrite.org/tutorials/writing-a-java-refactoring-recipe uses an option to define the fullyQualifiedClassName.
But the example does not show how to use that e.g. in a maven configuration or maven command line option.
(or am I missing some documentation?)

I made my recipe with option work with some kind of workaround, in my opinion:
first a `rewrite.yml` was needed:
```
---
type: specs.openrewrite.org/v1beta/recipe
name: MyRecipe
recipeList:
  - de.mobilcom.MyRecipe:
      fullyQualifiedClassName: de.mobilcom.Foobar
```
then execute the maven plugin with
```
mvn -DskipMavenParsing=true -Drewrite.configLocation=rewrite.yml -Drewrite.activeRecipes=MyRecipe rewrite:run
```

So, how should recipes with mandatory options be defined in maven configuration or executed?

Best regards
Achim
