### DISCUSSION TITLE
Replace class1.method1 with class2.method2 using open rewrite

### DISCUSSION THREAD

**Discussion by Lipuxy** [openrewrite/rewrite#3712] [Q&A] [answered]
Rename/replace all references of  class1.method1 with class2.method2 using open rewrite

**Comment by timtebeek** [comment, marked as answer]
You can combine existing building block recipes through [our recipe builder](https://app.moderne.io/recipes/builder)
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.github.timtebeek
displayName: Rename class and method
description: Example
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: foo.Class1
      newFullyQualifiedTypeName: bar.Class2
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: bar.Class2 foo()
      newMethodName: bar.Class2 bar()
```
There's more documentation available here: https://docs.openrewrite.org/authoring-recipes/types-of-recipes

Hope that helps!
