### DISCUSSION TITLE
Recipe ReplaceAnnotation doesn't replace full qualified name

### DISCUSSION THREAD

**Discussion by rregout** [openrewrite/rewrite#4314] [Q&A] [answered]
I have created a rewrite.yml with the following recipe list:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.ReplaceSingletonAnnotation
displayName: Replace annotation example
recipeList:
  - org.openrewrite.java.ReplaceAnnotation:
      annotationPatternToReplace: '@javax.ejb.Singleton'
      annotationTemplateToInsert: '@org.springframework.stereotype.Component'
```

With this a simple module project:

A parent pom:

```xml
<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>parent-project</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>services</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>javax</groupId>
                <artifactId>javaee-api</artifactId>
                <version>7.0</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.3.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
```

and a module pom:

```xml
<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.example</groupId>
        <artifactId>parent-project</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>services</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

</project>
```

And within the module an example Java class:

```java
package com.example;

import javax.ejb.Singleton;

@Singleton
public class SingletonExample {

}
```

After running the command `mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=com.example.ReplaceSingletonAnnotation` the result is the SingletonExample class with:

```java
package com.example;

@org.springframework.stereotype.Component
public class SingletonExample {

}
```

Why is a full qualified name added and not an import to Component?
