### DISCUSSION TITLE
Use the recipe ChangeParentPom and change only the artifactID

### DISCUSSION THREAD

**Discussion by Saturas89** [openrewrite/rewrite#4357] [Q&A] [answered]
Hi,

I tried to change the parent pom in our projects. Instead of "de.groupId.health-parent-jdk11" i would like to have "de.groupId.health-parent-jdk17".  The newVersion attribut seems to disturb, but its a mandatory field.
Has anyone an idea?

My last try was this:

```yaml
- org.openrewrite.maven.ChangeParentPom:
    oldGroupId: de.groupId
    oldArtifactId: health-parent-jdk11
    newGroupId: de.groupId
    newArtifactId: health-parent-jdk17
    newVersion: HEAD-SNAPSHOT
```
