### DISCUSSION TITLE
"ReplaceSupportClassWithItsInterface" but interface is not yet (only after the migration) in classpath for Java visitor

### DISCUSSION THREAD

**Discussion by ghost** [openrewrite/rewrite#4398] [Q&A] [answered]
Hi OpenRewrite experts,

during migration from Hibernate 5 to Hibernate 6 (plus Spring 2 to 3 and EE8 to EE10), we need to replace a **Hibernate "final resulting SQL" interceptor**
```
public class QueryHintInterceptor extends org.hibernate.EmptyInterceptor {
    (...)
    @Override
    public String onPrepareStatement(final String sql) {
    (...)
    }
}
```
by this:
```
public class QueryHintInterceptor implements org.hibernate.resource.jdbc.spi.StatementInspector {
    (...)
    @Override
    public String inspect(String sql) {
    (...)
    }
}
```
Obviously, the "org.openrewrite.java.spring.batch.**ReplaceSupportClassWithItsInterface**" would be a great candidate recipe to do this, but it won't work, and I am wondering whether I am assuming correctly that it's due to the following problem:

Before migration, in the old Hibernate 5 world as seen by the Rewrite Java vistor, the **new Hibernate 6-only target interface does not exist yet as a visitable class in the classpath** (it is only provided with Hibernate 6).

How would you recommend to resolve my specific issue? "Simply" using recipes based on regexp replacements afaik creates too many issues due to e.g. package import statements, but if possible, I'd like to avoid having to write a Java recipe...

Many thanks for your feedback/opinions on this - much appreciated! 😄 👍

**Comment by timtebeek** [comment, marked as answer]
hi! We have an approach specifically for when you need [more than one major version on the classpath](https://docs.openrewrite.org/authoring-recipes/multiple-versions) for your recipes; That's also been integrated into rewrite-hibernate as you can see [here](https://github.com/openrewrite/rewrite-hibernate/tree/main/src/main/resources/META-INF/rewrite/classpath) and [here](https://github.com/openrewrite/rewrite-hibernate/blob/b87efb46792022f2a58abbf08b0e7e1ce224d8ad/build.gradle.kts#L9-L10). It sounds like the recipe you need would be a great addition there; and if you open a draft PR we'll gladly help you set up the steps you can't already work out using these hints. Let's continue on an issue or draft PR in rewrite-hibernate. :)

**Comment by ghost** [comment]
Hmm - great suggestion, unfortunately at this moment, due to pressing deadlines to get our full EE10/Spring 3/Hibernate 6 migration done, I won't have enough time to do it the fully correct and publicly reusable way, as this would indeed require more time to implement some medium complex Java recipe addition with the (great! :clap:) "classpathFromResources" feature I hadn't been fully aware of before.

I think I have a reasonably good idea of how this will have to be implemented, though, so once I have enough spare cycles (which won't be before mid-October unfortunately), I cannot promise, but am definitely tempted to get back to adding this (even though our own migration will likely be done by then!)...

Sorry for being unable to provide something of general use right now under the present time pressure... :cry:

**Reply by timtebeek** [reply]
All good and understandable; glad my hints at least are proving valuable; know that you're also welcome to provide a rough draft and then we can try to take over from there. The reason I nudge towards PRs is that it's a lot easier for me to help out when I can see and run the code, and directly push suggestions & fixes. It's of course no requirement to get help, but it does make things easier.

Good luck with the migration there, and hope to be in touch!

**Reply by ghost** [reply]
I'm about to come up with a sequence of "FindAndReplace" which resolves it the "quick and dirty" way for me, will post it here for reference...

**Reply by ghost** [reply]
Here is my pragmatic quick and dirty solution for the above issue until there is more time to deal with the proper one as described above (note that I restricted "filePattern" to only apply all "FindAndReplace" on the single project-specific Java source I need it to rewrite)...

```
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.hibernate.interceptor.ReplaceEmptyInterceptorOnPrepareStatementWithInterfaceStatementInterceptor
recipeList:
  - org.openrewrite.text.FindAndReplace:
      find: \bextends\s((org\.hibernate\.)*)EmptyInterceptor\b
      replace: implements $1StatementInspector
      regex: true
      filePattern: "**/QueryHintInterceptor.java"
  - org.openrewrite.text.FindAndReplace:
      find: org.hibernate.EmptyInterceptor
      replace: org.hibernate.resource.jdbc.spi.StatementInspector
      filePattern: "**/QueryHintInterceptor.java"
  - org.openrewrite.text.FindAndReplace:
      find: EmptyInterceptor
      replace: StatementInspector
      filePattern: "**/QueryHintInterceptor.java"
  - org.openrewrite.text.FindAndReplace:
      find: org.hibernate.StatementInspector
      replace: org.hibernate.resource.jdbc.spi.StatementInspector
      filePattern: "**/QueryHintInterceptor.java"
  - org.openrewrite.text.FindAndReplace:
      find: \bonPrepareStatement\(.*\sString\s+(\w+)\s*\)
      replace: inspect(String $1)
      regex: true
      filePattern: "**/QueryHintInterceptor.java"
```

Works at least for me/us... 😉
