### DISCUSSION TITLE
Unwanted variable expansion in recipe

### DISCUSSION THREAD

**Discussion by gsmet** [openrewrite/rewrite#4428] [Q&A] [answered]
Hi,

I'm trying to implement this relatively simple recipe:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.quarkus.updates.core.quarkus313.UpdateTestOIDCAuthServerUrl
recipeList:
  - org.openrewrite.properties.ChangePropertyValue:
      propertyKey: '%test.quarkus.oidc.auth-server-url'
      oldValue: '${keycloak.url}/realms/quarkus/'
      newValue: '${keycloak.url:replaced-by-test-resource}/realms/quarkus/'
```

The important part is `${keycloak.url:replaced-by-test-resource}`.
I wouldn't expect any variable expansion taking place, given I don't provide any properties but given a default value is provided in my expression, it is resolved anyway and I end up with my tests failing with:

```
diff --git a/src/main/resources/application.properties b/src/main/resources/application.properties
index 195e75a..b32d565 100644
--- a/src/main/resources/application.properties
+++ b/src/main/resources/application.properties
@@ -1 +1 @@ 
-%test.quarkus.oidc.auth-server-url=${keycloak.url:replaced-by-test-resource}/realms/quarkus/
\ No newline at end of file
+%test.quarkus.oidc.auth-server-url=replaced-by-test-resource/realms/quarkus/
\ No newline at end of file
] 
expected: "%test.quarkus.oidc.auth-server-url=${keycloak.url:replaced-by-test-resource}/realms/quarkus/"
 but was: "%test.quarkus.oidc.auth-server-url=replaced-by-test-resource/realms/quarkus/"
```

I see that there is a `propertyPlaceholderHelper` used when loading resources and I suppose that's what is at play here. I tried various way to escape my expression and couldn't find something that would work (and for which I don't end up with a `\` in my output).

Any advice on how to address this?

Thanks!

**Comment by timtebeek** [comment, marked as answer]
Did you already try the `-Drewrite.resolvePropertiesInYaml=false` option on the Maven plugin?
https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html#resolvePropertiesInYaml

**Reply by gsmet** [reply]
For now I'm not even at the Maven level, I'm trying to get this to work with my tests.

I'm simply loading the resource with `spec.recipeFromResource(path, myActiveRecipes)`.

From what I can see, all that the Maven property does is to not pass the Maven properties to the YAML loader. In my case, I'm passing an empty `Properties` to the YAML loader but... there is a default value for the expansion which seems to trigger the expansion anyway.

I'm not against this behavior but I need a way to somehow escape the property expansion in this case.

**Reply by gsmet** [reply]
Typically, I wouldn't have any issue adding `\` here but... they are not dropped from the output.

**Comment by Orbifoldt** [comment]
I thought I'd give it a go to find a fix, but this unit test I started with is passing:
```java
    @Test
    void doNotExpandNewValue() {
        rewriteRun(
          spec -> spec.recipe(new ChangePropertyValue("my.prop", "${keycloak.url:replaced-by-test-resource}/realms/quarkus/", "${keycloak.url}/realms/quarkus/", null, null)),
          properties(
            "my.prop=${keycloak.url}/realms/quarkus/",
            "my.prop=${keycloak.url:replaced-by-test-resource}/realms/quarkus/"
          )
        );
    }
```
I don't know enough about the context in which the unit tests run vs how openrewrite is triggered normally (or how quarkus is using openrewrite, for that matter), any clue on how to trigger this same behaviour in a test?

**Reply by gsmet** [reply]
Yes, the problem is when loading the recipes from YAML. It’s then that the property is expansion is done. 
From Java, everything is fine.

**Reply by Orbifoldt** [reply]
Ah, now I understand, it happens earlier already

I think I have a workaround (not very pretty): you can use the regex mode to capture (for example) the dollar sign in a capturing group, and then insert that into the new value:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.quarkus.updates.core.quarkus313.UpdateTestOIDCAuthServerUrl
recipeList:
  - org.openrewrite.properties.ChangePropertyValue:
      regex: true
      propertyKey: '%test.quarkus.oidc.auth-server-url'
      oldValue: '(\$)\{keycloak.url}\/realms\/quarkus\/'
      newValue: '$1{keycloak.url:replaced-by-test-resource}/realms/quarkus/'
```
So, in the new value, the `$1` is replaced with the first capturing group, which captured the symbol `$`. Since we never have the substring `${` in this yaml, nothing will get expanded!
