### DISCUSSION TITLE
How to use org.openrewrite.xml.format.NormalizeTabsOrSpaces? It doesn't seem to work.

### DISCUSSION THREAD

**Discussion by renannprado** [openrewrite/rewrite#5197] [Q&A]
The [documentation](https://docs.openrewrite.org/recipes/xml/format/normalizetabsorspaces) says that this recipe takes no parameters, but when I run it does not do anything.

This is the complete recipe I tried, but trying it alone also doesn't work. I tried with and without the style.

```yaml
---
type: specs.openrewrite.org/v1beta/style
name: com.example.TestStyle
styleConfigs:
  - org.openrewrite.xml.style.TabsAndIndentsStyle:
      useTabCharacter: false
      indentSize: 8
      continuationIndentSize: 8
---
type: specs.openrewrite.org/v1beta/recipe
name: com.example.TestRecipe
recipeList:
  - org.openrewrite.maven.RemoveRepository:
      id: gitlab-maven
  - org.openrewrite.maven.RemoveUnusedProperties:
      propertyPattern: .*CI_API_V4_URL.*
  - org.openrewrite.maven.RemoveUnusedProperties:
      propertyPattern: .*CI_PROJECT_ID.*
  - org.openrewrite.maven.AddRepository:
      id: gitlab-maven
      url: https://example.com/api/v4/groups/123/-/packages/maven
      snapshotsUpdatePolicy: always
      snapshotsEnabled: true
  - org.openrewrite.xml.format.NormalizeTabsOrSpaces
```

I tried the below:

```bash
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=org.openrewrite.xml.format.NormalizeTabsOrSpaces -Drewrite.activeStyles=com.example.TestStyle
```

```bash
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=com.example.TestRecipe -Drewrite.activeStyles=com.example.TestStyle
```
