### DISCUSSION TITLE
Wildcard in Fully Qualified Paths?

### DISCUSSION THREAD

**Discussion by m-brophy** [openrewrite/rewrite#851] [Q&A] [answered]
Is it possible to use wildcards in a path definition in rewrite.yml? I'm looking to provide a recipe to convert imports of one version of library code to another, where the difference is a consistent change to fully qualified path name. There are a lot of classes in the library and rather than provide thousands of lines of change definitions, one line for each class, it would be good to be able to do something like this:

`---
type: specs.openrewrite.org/v1beta/recipe
name: org.mine.LibraryUpgradeRecipe
displayName: Change type example
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.mine.child.foo.*
      newFullyQualifiedTypeName: org.mine.foo.*`

**Comment by jkschneider** [comment, marked as answer]
@m-brophy Hi! There is a `org.openrewrite.java.ChangePackage` recipe that is designed for this purpose.

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.mine.LibraryUpgradeRecipe
displayName: Change library package example
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: org.mine.child.foo
      newPackageName: org.mine.foo
```
