### ISSUE TITLE
Unexpected changes to double # character (##) and /# characters during recipe run 

### ISSUE THREAD

**Issue by chrismhess** [openrewrite/rewrite#1020]
When running a recipe we get the following changes to instances of # characters in properties files

example of removal of # from /#
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle**/#**boot-features-jersey
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle**/**boot-features-jersey

example of double # to single # 
**##**chassis.management.metrics.export.cloudwatch.awsAccessKey
**#**chassis.management.metrics.export.cloudwatch.awsAccessKey

**Recipe being used:** 

```
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing
displayNames: Testing
description: Testing
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: org.assertj
      artifactId: assertj-core
      version: 3.x
      scope: test
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: server.port
      newPropertyKey: chassis.name
  - org.openrewrite.properties.ChangePropertyValue:
      propertyKey: server.tomcat.accesslog.enabled
      newValue: true
```
