### ISSUE TITLE
Problem when applying the ChangePropertyKey recipe on a list

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1097]
Good afternoon,

I am having problems applying ChangePropertyKey recipe on a list. In my example, I am trying to apply the following recipes:

```
---
type: specs.openrewrite.org/v1beta/recipe
name: darwin.example.Migrate
displayName: Migrate Example
description: 'Migrate properties found in `application.properties` and `application.yml`.'
recipeList:
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: es.santander.nuar.logging.appKey
      newPropertyKey: darwin.app-key
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: es.santander.nuar.util.remote.ws.security.types
      newPropertyKey: darwin.webservices.security-types
```
on the following YAML:

```
es:
  santander:
    nuar:
      logging:
        appKey: nuar
      util:
        remote:
          ws:
            security:
              types:
                - name: userNameA
                  mode: userNameAToken
                  user: "11535750P"
                  password: "14725836"
                - name: userNameB
                  mode: userNameBToken
                  user: "11535750B"
                  password: "14725837"
```

and as a result I get:

```
es.santander.nuar.logging.appKey: nuar
darwin.webservices.security-types:
                - name: userNameA
                  mode: userNameAToken
                  user: "11535750P"
                  password: "14725836"
                - name: userNameB
                  mode: userNameBToken
                  user: "11535750B"
                  password: "14725837"
```

As you can see, there is no change in the property "**es.santander.nuar.logging.appKey**". Can you tell me, please, what could be happening and if I am misapplying any recipe.

Thank you very much

**Comment by traceyyoshima** [comment]
@josemariavillar, a similar suggestion here.

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: darwin.example.Migrate
displayName: Migrate Example
description: 'Migrate properties found in `application.properties` and `application.yml`.'
recipeList:
  - org.openrewrite.yaml.CoalesceProperties
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: es.santander.nuar
      newPropertyKey: darwin
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: darwin.logging.appKey
      newPropertyKey: darwin.app-key
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: darwin.util.remote.ws.security.types
      newPropertyKey: darwin.webservices.security-types
```

`org.openrewrite.yaml.CoalesceProperties` will collect the common keys at the root:
```yaml
es.santander.nuar:
  logging.appKey: nuar
  util.remote.ws.security.types:
    - name: userNameA
      mode: userNameAToken
      user: "11535750P"
      password: "14725836"
    - name: userNameB
      mode: userNameBToken
      user: "11535750B"
      password: "14725837"
```

The first ChangePropertyKey recipe will create a common root to work from:
```yaml
darwin:
  logging.appKey: nuar
  util.remote.ws.security.types:
    - name: userNameA
      mode: userNameAToken
      user: "11535750P"
      password: "14725836"
    - name: userNameB
      mode: userNameBToken
      user: "11535750B"
      password: "14725837"
```
Then the remaining ChangePropertyKey recipes generate your desired results! :)
```yaml
darwin:
  app-key: nuar
  webservices.security-types:
    - name: userNameA
       mode: userNameAToken
       user: "11535750P"
       password: "14725836"
   - name: userNameB
      mode: userNameBToken
      user: "11535750B"
      password: "14725837"
```
