### ISSUE TITLE
Problem when applying the ChangePropertyKey recipe

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1114]
Good afternoon,

I am having problems applying ChangePropertyKey recipe on a list. In my example, I am trying to apply the following recipes:

```YAML
---
type: specs.openrewrite.org/v1beta/recipe
name: example.migrationassistant.MigrateProperties
displayName: Migrate properties
description: 'Migrate properties found in `application.properties` and `application.yml`.'
recipeList:
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: darwin.logging.activity
      newPropertyKey: darwin.logging.activity.enabled
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: darwin.omnichannel.header
      newPropertyKey: darwin.omnichannel.header.channel
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: darwin.omnichannel.parameter
      newPropertyKey: darwin.omnichannel.parameter.channel
```

on the following YAML:

``` YAML
darwin:
  logging:
    functional:
      loggedEndpoints: '/hello'
    activity: true 
    environment: CERT 
  omnichannel:
      parameter: "channel"
      header: "X-Santander-Channel"
  app-key: nuar
```

and as a result I get:

``` YAML
darwin:
  logging:
    functional:
      loggedEndpoints: '/hello'
    activity: true
    environment: CERT
  omnichannel:
      parameter: "channel"
      header: "X-Santander-Channel"
  app-key: nuar
```

As you can see, the indicated recipes are not being applied correctly. Can you tell me, please, what could be happening and if I am misapplying any recipe.

Thank you very much

**Comment by aegershman** [comment]
@josemariavillar the PR merged in https://github.com/openrewrite/rewrite/pull/1115 will fix this. Now after running your recipes, the output _should_ look like this:

```yml
darwin:
  logging:
    functional:
      loggedEndpoints: '/hello'
    activity.enabled: true
    environment: CERT
  omnichannel:
      parameter.channel: "channel"
      header.channel: "X-Santander-Channel"
  app-key: nuar
```

This fix will be included in the next main release. Until then, you could use the latest `rewrite` snapshot version, which has this fix. Thank you for logging this, it really does help improve things 👍  I'm going to go ahead and close this, but please @ me if you have any other questions or feel like this should be re-opened 👍
