### ISSUE TITLE
Issue discovered with `.travis.yml` on CoalesceProperties left-shift

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#1133]
### Problem
> Describe the issue you are experiencing.

(This issue / diff provided is _before_ having merged https://github.com/openrewrite/rewrite/pull/1132 and will check this result again after executing the most recent code from it.)

The comments succeeding `matrix.include` should be shifted left in its entirety.

### Expected behavior
> Describe what you expected to see.

I _believe_ this should be...

```yml
matrix.include:
# On OSX, run with default JDK only.
# - os: osx
# On Linux we install latest OpenJDK 1.8 from Ubuntu repositories
- name: Linux x86_64
  arch: amd64
```

### Example diff
```diff
-matrix:
-  include:
-  # On OSX, run with default JDK only.
+matrix.include:
+# On OSX, run with default JDK only.
   # - os: osx
   # On Linux we install latest OpenJDK 1.8 from Ubuntu repositories
   - name: Linux x86_64
-    arch: amd64
+  arch: amd64
 #  - name: Linux aarch64
 #    arch: arm64

```

#### Recipes in example diff:
- org.openrewrite.yaml.CoalesceProperties

### References:
- Recipe ID: `dGlV5`
- Recipe Name: "Coalesce YAML properties"
- Repository: apache/rocketmq
- Created at Wed Oct 20 2021 20:06:30 GMT-0500 (Central Daylight Time)
