### ISSUE TITLE
Error processing yaml comments

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1142]
Hi,

I am testing with version 4.15.0-SNAPSHOT of rewrite-maven-plugin and 7.16.0-SNAPSHOT of rewrites.

This is the example yaml
```yaml
com:
  company:
    other:
      name: project-test  # prueba2
      logging:
        kafka:
          uniqueTopic: a-topic #pppp
#TODO bug pending          topic: a-topic #This property disappear
          properties:
            one.other: true  #prueba
            two.seconds: "darling"
```

I use this recipe
```yaml
  - org.openrewrite.yaml.DeleteProperty:
      propertyKey: com.company.other.name
      coalesce: true
```

And this is the yaml result
