### ISSUE TITLE
Yaml comment join to boolean value

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1143]
Hi,

I am testing with version 4.15.0-SNAPSHOT of rewrite-maven-plugin and 7.16.0-SNAPSHOT of rewrites.

This is the example yaml
```yaml
com:
  company:
    other:
      name: project-test  # prueba2
      logging:
        kafka:
          uniqueTopic: a-topic #pppp
#TODO bug pending          topic: a-topic #This property disappear
          properties:
            one.other: true  #prueba
            two.seconds: "darling"
```

I use this recipe
```yaml
  - org.openrewrite.yaml.DeleteProperty:
      propertyKey: com.company.other.name
      coalesce: true
```

And this is the result
```
diff --git "a/src\\main\\resources\\config\\application.yml" "b/src\\main\\resources\\config\\application.yml"
index f3c726f..5f8c333 100644
--- "a/src\\main\\resources\\config\\application.yml"
+++ "b/src\\main\\resources\\config\\application.yml"
@@ -1,13 +1,8 @@ org.openrewrite.yaml.DeleteProperty
-com:
-  company:
-    other:
-      name: project-test  # prueba2
-      logging:
-        kafka:
-          uniqueTopic: a-topic #pppp
+com.company.other.logging.kafka:
+  uniqueTopic: a-topic #pppp
 #TODO bug pending          topic: a-topic #This property disappear
-          properties:
-            one.other: true  #prueba
-            two.seconds: "darling"  #last
+  properties:
+    one.other: true#prueba
+    two.seconds: "darling"  #last
```

Note that line "one.other: true#prueba" is not a valid comment

The complete example is in https://github.com/ruben-garciapariente/test-openwrite/tree/13b80b7a3b53e276eb4fbfb2b604fe6276d538d7

Thanks & regards
