### ISSUE TITLE
problem when deleting certain properties Kebab Case vs Camel Case

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1168]
Good afternoon,

I have problems deleting certain properties with the DeleteProperty recipe, which I define as Kebab Case and in the Yaml properties file is defined as Camel Case, or vice versa.

For example, if I want to delete the property "darwin.extended-error.error-translate-url", and in the Yaml file is defined as "darwin.extended-error.errorTranslateUrl" the recipe does nothing.

A possible solution would be to use the CaseFormat from Guava:

https://github.com/openrewrite/rewrite/blob/9b88b82839fcd0a6cded77672fc1d5561336b1ca/rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java#L86-L95

I think it also affects the ChangePropertyKey recipe.

**Comment by aegershman** [comment]
Thanks for logging this @josemariavillar we'll take a look 👍

**Comment by josemariavillar** [comment]
As far as I have been able to verify, the same thing happens in the DeleteProperty and ChangePropertyKey of the Yaml file or property files.

**Comment by aegershman** [comment]
@josemariavillar so just to make sure I understand what you mean, you're saying you are configuring the recipe as `DeleteProperty("darwin.extended-error.error-translate-url")` and expecting it to delete the key `darwin.extended-error.errorTranslateUrl`? As far as I'm aware, at least in yaml, `errorTranslateUrl` and `error-translate-url` are not the same yaml key by reference, so it'd be a little unexpected to have it affect both `errorTranslateUrl` and `error-translate-url`.

You could just add another `DeleteProperty` recipe to the list, as in:

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.DeletePropertyExample
displayName: Delete Property example
recipeList:
  - org.openrewrite.yaml.DeleteProperty:
      propertyKey: darwin.extended-error.error-translate-url
  - org.openrewrite.yaml.DeleteProperty:
      propertyKey: darwin.extended-error.errorTranslateUrl
```

Let me know if that would that work for your situation? 👍
