### ISSUE TITLE
ChangePropertyKey overwrites an existing key

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1249]
Hello,

I am using the ChangePropertyKey recipe and I don't know if there is a bug or I am using it incorrectly.

My source yaml is
```yaml
root:
  stuff0:
    field0: value0

other:
  field0: value0
  field1: value1
```

My recipe is

```yaml
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: other
      newPropertyKey: root.stuff1
```

I expect something like
```yaml
root:
  stuff0.field0: value0
  stuff1:
    field0: value0
    field1: value1
```

but the real result is 
```yaml
root.stuff0.field0: value0

root.stuff1:
  field0: value0
  field1: value1
```

Is the behavior of ChangePropertyKey correct? 
If it is, is there any way to get the result I expect?

We have a complete example in https://github.com/ruben-garciapariente/test-openwrite/tree/ChangePropertyKey-yaml

Thank you very much
