### ISSUE TITLE
Support matching sequences in JsonPathMatcher

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#1252]
Enhance JsonPathMatcher to find sequences in a document.

**Comment by pway99** [comment]
re-opening to support #1419

**Comment by pway99** [comment]
re-closing since the goal for this issue was to use JsonPathMatcher for matching either a specific price or all of the prices from the following YAML which is not related to #1419.

```YAML
store:
  book:
    - category: reference
       author: Nigel Rees
       title: Sayings of the Century
       prices: [8.95, 9.95, 10.95]
```
