### ISSUE TITLE
Merge recipe with sequences bad indent

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1275]
Hello,

I am using the org.openrewrite.yaml.MergeYaml recipe and apparently it is not indenting the sequences correctly.

My source yaml is

```yaml
com:
  key1: value1
  key2: value2
  key3: value3
```
My recipe is

```yaml
  - org.openrewrite.yaml.MergeYaml:
      key: "$"
      yaml: >
        darwin:
          logging:
          - 1
          - 2
      acceptTheirs: true
      fileMatcher: "**/application*.yml"
```

I expect something like

```yaml
com:
  key1: value1
  key2: value2
  key3: value3
darwin:
  logging:
    - 1
    - 2
```

but in the actual execution we see that the second value of the sequence has more spaces on the left than the first one.

```yaml
com:
  key1: value1
  key2: value2
  key3: value3
darwin:
  logging:
    - 1
      - 2
```

We have a complete example in https://github.com/ruben-garciapariente/test-openwrite/tree/merge-sequence-bug

Thank you very much
