### ISSUE TITLE
Encoding problems when applying recipes to files with non-ascii characters

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1282]
Hello,

We hava a yaml file in utf-8 format with a non-ascii caracter. In this case "É"

```yaml
com:
  key1: TÉCNICA
  key2: value2
  key3: value3
```

We apply a  DeleteKey recipe (It also happens with other recipes (we have tested with MergeYaml and ChangePropertyKey).
```yaml
  - org.openrewrite.yaml.DeleteKey:
      keyPath: $.com.key2
      fileMatcher: "**/application.yml"
```

The result file 
```yaml
com:
  key1: TÃ‰CNICA
  key3: value3
```

As you can see the character É is coded wrongly

There is an example in https://github.com/ruben-garciapariente/test-openwrite/tree/issue-non-ascii-characters

Thank you very much
Regards

**Comment by traceyyoshima** [comment]
Hi @ruben-garciapariente, thanks for reporting the issue!

I ran the recipe example from the branch with the latest changes on main and got different results:
```yaml
com:
  key1: TÉCNICA
  key3: value3
```
Would you mind testing this again?
Thanks in advance!
