### ISSUE TITLE
New Recipe: AddManagedDependency

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite#1286]
I was looking to use AddDependency to add a BOM file into the dependencyManagement section.

I'd even argue that when the scope is `import` and the type is `pom` that the default should be to place and/or create it in dependencyManagement as most often that's the intention.

Here's the sample of what I was trying to accomplish:

```
- org.openrewrite.maven.AddDependency:
        groupId: org.apache.logging.log4j
        artifactId: log4j-bom
        version: 2.16.0
        scope: import
        type: pom
        onlyIfUsing: org.apache.logging.*
        releasesOnly: true
```

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
