### ISSUE TITLE
Merge recipe with sequences within map bad indent 

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1292]
Hello,

I am using the org.openrewrite.yaml.MergeYaml recipe and apparently it is not indenting the sequences correctly.

My source yaml is

```yaml
noncore:
  key1: value01
```
My recipe is

```yaml
  - org.openrewrite.yaml.MergeYaml:
      key: "$"
      yaml: >
        core:
          - map2:
              value:
                - 1
                - 2
      acceptTheirs: true
      fileMatcher: "**/application*.yml"
```

I expect something like

```yaml
noncore:
  key1: value01
core:
  - map2:
      value:
        - 1
        - 2
```

But in the execution we see that the sequence that is inside a map has wrong identation

```yaml
noncore:
  key1: value01
core:
  - map2:
      value:
  - 1
  - 2
```

We have a complete example in https://github.com/ruben-garciapariente/test-openwrite/tree/merge-sequence-bug-2

We are testing with 7.17.0-SNAPSHOT, if we test with version 7.16.0 we have the issue fixed in https://github.com/openrewrite/rewrite/issues/1275

Thank you very much
