### ISSUE TITLE
Create an application.yml file if it does not exist

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1300]
A question; Is there a recipe to create an application.yml file? It would be very useful if there is a recipe to create an application.yml file, if it does not exist.

**Comment by pway99** [comment]
Hi @josemariavillar, Yes checkout the `CreateTextFile` recipe.  

Here is an example createTextFile declarative recipe.
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.addApplicationYaml
displayName: Add Yaml File
description: Add application.yml if it does not exist.
recipeList:
  - org.openrewrite.text.CreateTextFile:
      fileContents: application.name=bla
      relativeFileName: src/main/resources/application.yml
      overwriteExisting: "false"
``` 

https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
