### ISSUE TITLE
Merge recipe with sequences of map within map 

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1302]
Hello,

I am using the org.openrewrite.yaml.MergeYaml recipe and apparently it is not indenting the sequences correctly.

My source yaml is

```yaml
com:
  key1: value1
  key3: value3
testino:
  core:
    key1: value01
```
My recipe is

```yaml
  - org.openrewrite.yaml.MergeYaml:
      key: "$"
      yaml: |-
        testino:
          mmap4:
            - mmmap1: v111
              mmmap2: v222
            - nnmap1: v111
              nnmap2: v222
      fileMatcher: "**/application*.yml"
```

I expect something like

```yaml
testino:
  core:
    key1: value01
  mmap4:
     - mmmap1: v111
       mmmap2: v222
     - nnmap1: v111
       nnmap2: v222
```

But in the execution we see that the sequence that is inside a map has wrong identation

```yaml
testino:
  core:
    key1: value01
  mmap4:
     - mmmap1: v111
       mmmap2: v222
       - nnmap1: v111
         nnmap2: v222
```

We have a complete example in https://github.com/ruben-garciapariente/test-openwrite/tree/merge-sequence-bug3

I am testing with 7.17.0-SNAPSHOT and 7.16.0, and the issue is the same

Thank you very much
