### ISSUE TITLE
Error with the recipe Merge with the end of lines

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite#1303]
Hello

I work on windows and as you know by default the end of line is CRLF. 

I have a recipe defined in a CRLF format file.
```yaml
- org.openrewrite.yaml.MergeYaml:
      key: "$"
      yaml: |-
        com:
          key2: value1
      fileMatcher: "**/application*.yml"
```

and I have a file defined in a CRLF format file.
```yaml
com:
  key1: value1
  key3: value3
```

when applying mvn rewrite:run it is observed that the resulting application.yml file has CRLF end of line, except for the previous line where the new value is inserted which has LF
```yaml
com:^M
  key1: value1^M
  key3: value3
  key2: value1^M
```
Note: ^M indicate line has a CR, all rest lines have a LF

I have an example in https://github.com/ruben-garciapariente/test-openwrite/tree/merge-eol , but you have to run it with the git configured so that the text files end in CRLF (I think it is the default configuration in windows).

Thank you very much and best regards
