### ISSUE TITLE
Configurable RemoveUnusedLocalVariables with ignorable local variable names

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#1332]
Breaking this feature out from https://github.com/openrewrite/rewrite/issues/1278

Enable configuring RemoveUnusedLocalVariables with an array of ignorable variable names.

E.g., 

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.example.Example
displayName: example
description: Example description describing this example (description) ((example))
recipeList:
- org.openrewrite.java.cleanup.RemoveUnusedLocalVariables:
     ignoreVariablesNamed: ["unused"]
```
