### ISSUE TITLE
Maven: Remove comments in pom.xml

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1392]
Good afternoon,

When running the recipes that update the POM file, you are deleting comments that existed in the original POM and which I understand should not be deleted.

Example in https://github.com/josemariavillar/test_project

The original POM is:

```
	<name>Test Project</name>
	<description>Test Project</description>

	<!-- Use starter parent -->
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.12.RELEASE</version>
	</parent>

	<properties>
		<rewrite-maven-plugin.version>4.17.4</rewrite-maven-plugin.version>
	</properties>

	<dependencies>
		<!-- Spring framework dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

The recipes to run are:

```
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.UpgradePom
displayName: Upgrade POM
recipeList:

  - org.openrewrite.maven.AddDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-webflux
      version: 2.3.12.RELEASE
      onlyIfUsing: org.springframework.boot.*

  - org.openrewrite.maven.AddDependency:
      groupId: org.springframework.boot
      artifactId: spring-cloud-starter-config
      version: 2.2.8.RELEASE
      onlyIfUsing: org.springframework.boot.*
```
The result as you can see two of the three comments that existed in the file are removed:

```
diff --git a/pom.xml b/pom.xml
index 97d5316..2e16472 100644
--- a/pom.xml
+++ b/pom.xml
@@ -23,7 +23,6 @@ org.openrewrite.maven.AddDependency, org.openrewrite.maven.AddDependency
 	</properties>
 
 	<dependencies>
-		<!-- Spring framework dependencies -->
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-actuator</artifactId>
@@ -31,9 +30,16 @@
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-web</artifactId>
+		</dependency>
+		<dependency>
+			<groupId>org.springframework.boot</groupId>
+			<artifactId>spring-boot-starter-webflux</artifactId>
+		</dependency>
+		<dependency>
+			<groupId>org.springframework.boot</groupId>
+			<artifactId>spring-cloud-starter-config</artifactId>
+			<version>2.2.8.RELEASE</version>
 		</dependency>
-
-		<!-- Test dependencies -->
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-test</artifactId>
```

Thank you very much for the excellent support you provide

Thanks & regards
