### ISSUE TITLE
maybeUpdateModel: [WARNING] No version provided for dependency

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1455]
Good morning, 

I am having problems running the group of recipes that I had defined when testing with version 7.20.0-SNAPSHOT. In my case the first thing I do is to make a change of parent in the POM, and then the rest of recipes leaving correct resulting POM taking into account the new parent. 

With this version, that in most of the maven recipes is included maybeUpdateModel method, which in addition to update the POM of the context, validates it. 

https://github.com/openrewrite/rewrite/blob/a160b46c7e79294ad9703611f45c9d56767037df/rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java#L172

Being an individual validation for each recipe, it causes that if at that moment the POM is not valid, an exception is generated, failing the execution of that recipe.

https://github.com/openrewrite/rewrite/blob/a160b46c7e79294ad9703611f45c9d56767037df/rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java#L486-L488

I attach a test case.

Child project: https://github.com/josemariavillar/test_project/tree/error_update_model
Parent project: https://github.com/josemariavillar/test-project-parent/tree/error_update_model

As you can see, in the following example, I run the following group of recipes where the first thing I do is to make a parent change and then remove those dependencies that are no longer needed and can cause problems:

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.test.project.UpdatePOM
displayName: Add update Maven example
recipeList:
  - org.openrewrite.maven.ChangeParentPom:
      oldGroupId: es.test.project
      newGroupId: org.springframework.boot
      oldArtifactId: test-project-parent
      newArtifactId: spring-boot-dependencies
      newVersion: 2.3.12.RELEASE

  - org.openrewrite.maven.RemoveDependency:
      groupId: io.springfox
      artifactId: springfox-swagger2

  - org.openrewrite.maven.RemoveDependency:
      groupId: io.springfox
      artifactId: springfox-swagger-ui

  - org.openrewrite.maven.RemoveDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-web
      
  - org.openrewrite.maven.AddDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-webflux
      version: 2.3.X
      onlyIfUsing: org.springframework.boot.*
```

The result obtained is:

```
[INFO] --- rewrite-maven-plugin:4.21.0-SNAPSHOT:dryRun (default-cli) @ test-openrewrite ---
[INFO] Using active recipe(s) [com.test.project.UpdatePOM]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Parsing Java main files...
[INFO] Parsing Java test files...
[INFO] Running recipe(s)...
[WARNING] No version provided for dependency io.springfox:springfox-swagger2
[WARNING] These recipes would make changes to pom.xml:
[WARNING]     org.openrewrite.maven.RemoveDependency
[WARNING]     org.openrewrite.maven.RemoveDependency
[WARNING]     org.openrewrite.maven.RemoveDependency
[WARNING]     org.openrewrite.maven.AddDependency
[WARNING] Patch file available:
[WARNING]     C:\test_project\target\site\rewrite\rewrite.patch
[WARNING] Run 'mvn rewrite:run' to apply the recipes.
```

As you can see, in this example, the **ChangeParentPom** recipe is not executed because an exception occurs when the version of the io.springfox:springfox-swagger2 dependency is not found, which will be removed later.

With version 7.17.1 it works without problems.
