### ISSUE TITLE
MergeYaml: Add option to match document based on current document

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1465]
Hi,

we have a feature request for the `MergeYaml` recipe. Currently it is not possible to have a condition on the YAML document itself only on the file. Therefor we would appreciate the possibility to have an optional condition for matching the document structure itself.

The reason for the feature request are the Spring boot multi document profiles. It is currently not possible to add new elements to a single document, e.g.
Merge
```
spring:
  application:
    group: group by merge
```
into
```
---
spring:
  application:
    name: my-name

---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: my-name-test
```

With the `MergeYaml` recipe you can only modify none or both documents but not e.g. the non-profile specific one.

Kind regards
Thomas
