### ISSUE TITLE
Replace 'Map.keyset().contains()' with 'Map.containsKey()' 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1584]
Before : 

```java
Map<Integer,Integer> map = Map.of(1,2);
boolean containsOne= map.keySet().contains(1)

```

After : 

```java
Map<Integer,Integer> map = Map.of(1,2);
boolean containsOne= map.containsKey(1)

```

**Comment by jkschneider** [comment]
Good opportunity to introduce you to `SimplifyCallChain`:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.cleanup.UseMapContainsKey
displayName: Use `Map#containsKey`
description: '`map.keySet().contains(a)` can be simplified to `map.containsKey(a)`.'
recipeList:
  - org.openrewrite.java.SimplifyMethodChain:
      methodPatternChain:
        - 'java.util.Map keySet()'
        - 'java.util.Set contains(..)'
      newMethodName: containsKey
```
