### ISSUE TITLE
OpenRewrite may not correctly detecting the import styles

### ISSUE THREAD

**Issue by luisrodval** [openrewrite/rewrite#1674]
Hi!
When executing rewrite:run if I change 5 or more types of the same package then it nests the imports with asterisk.
The problem is that sonar marks it as a critical issue.

Is there any way to prevent it from doing that?
Thank you!

**Comment by tkvangorder** [comment]
Hi @luisrodval , 

You can define your own styles in yaml: 

https://docs.openrewrite.org/reference/yaml-format-reference#styles

```
---
type: specs.openrewrite.org/v1beta/style
name: com.yourorg.NoStarImports
styleConfigs:
  - org.openrewrite.java.style.ImportLayoutStyle:
      classCountToUseStarImport: 9999
```

There are instructions on how to activate your style in the plugin configuration:

https://docs.openrewrite.org/reference/rewrite-maven-plugin
https://docs.openrewrite.org/reference/gradle-plugin-configuration

Hope this helps!

**Comment by tkvangorder** [comment]
@okundzich Had a valid point, rewrite should be detecting the import styles.

**Comment by tkvangorder** [comment]
@luisrodval You can use the above to work around the issue, but we are interested in your use case, as Rewrite should be detecting the import styles present in your code.

**Comment by luisrodval** [comment]
Hi,
I have created yml with:
```
	---
	########################################################################################################################
	# No star imports style.
	type: specs.openrewrite.org/v1beta/style
	name: com.santander.darwin.migrationassistant.NoStarImports
	styleConfigs:
	  - org.openrewrite.java.style.ImportLayoutStyle:
		  classCountToUseStarImport: 999
		  nameCountToUseStarImport: 999
```

In the plugin of pom.xml I use this tag:
	```
<activeStyles>
		<style>com.santander.darwin.migrationassistant.NoStarImports</style>
	</activeStyles>
```
When execute rewrite:run there this trace in console:
	_**[INFO] Using active recipe(s) [com.santander.darwin.migrationassistant.myRecipes]
	[INFO] Using active styles(s) [com.santander.darwin.migrationassistant.NoStarImports]**_

It seems try apply styles, but also trace this for each executed recipe:
	_**[WARNING] Expected to find a block to fit import into.**_

The recipes (org.openrewrite.java.ChangeType) not works when I use the new styles. What am I doing wrong?
Thank you.

**Comment by traceyyoshima** [comment]
Hi @luisrodval, the warning is caused by missing blocks in the layout style. I opened an issue and will track down the cause in a moment.

For now, I'd recommend using:
```yaml
  - org.openrewrite.java.style.ImportLayoutStyle:
      classCountToUseStarImport: 999
      nameCountToUseStarImport: 999
      layout:
        - import all other imports
        - <blank line>
        - import javax.*
        - import java.*
        - <blank line>
        - import static all other imports
```
