### ISSUE TITLE
Add a way to exclude some recipes from a compound recipe and/or from rewrite execution

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1714]
E.g. I would like to execute on my code this compound recipe https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/resources/META-INF/rewrite/static-analysis-cleanup.yml#L18 but exclude org.openrewrite.java.cleanup.HiddenField because it doesn't fit with the style decided by the team.

Currently I can only make my own copy of the compound recipe, but I won't benefit from upstream update.

A way to achieve that could to add an extra `excludedRecipeList` field in compound recipes : 
```yml
type: specs.openrewrite.org/v1beta/recipe
name: MyCustomCommonStaticAnalysis
recipeList:
  - org.openrewrite.java.cleanup.CommonStaticAnalysis
excludedRecipeList:
  - org.openrewrite.java.cleanup.HiddenField
```

There could also be an extra configuration option in maven plugin configuration to declare recipes to excludes from execution.
