### ISSUE TITLE
Rewrite-yaml: ChangePropertyKey not working correctly

### ISSUE THREAD

**Issue by ferblaca** [openrewrite/rewrite#1744]
I have found a case where the `ChangePropertyKey` method of `rewrite-yaml` is not working correctly.

I have a main recipe to which I am adding other recipes with the `doNext()` method as follows:

```
public class MainRecipe extends Recipe {

  public MainRecipe () {
    this.doNext(
        new ChangePropertyKey("app.foo.change.from", "app.bar.change.to", null,
            null));
  }
}
```

In this case I'm just adding the `ChangePropertyKey` recipe.

Based on this recipe, I show below some results of its execution according to the source .yml:

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>Yml source</th>
      <th>Yml result</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>

```yml
app:
  foo.change.from: hi
```

</td>
      <td>

```yml
app.bar.change.to: hi
```

</td>
      <td>OK</td>
    </tr>
    <tr>
      <td>2</td>
      <td>

```yml
app:
  foo.change.from: hi
  bar.other.property: bye
```

</td>
      <td>

```yml
app:
  bar.change.to: hi
  bar.other.property: bye
```

</td>
      <td>OK</td>
    </tr>
    <tr>
      <td>3</td>
      <td>

```yml
app:
  foo.change.from: hi
  bar:
    other:
      property: bye
```

</td>
      <td>

```yml
app:
  foo.change.from: hi
  bar:
    other:
      property: bye
```

</td>
      <td>KO!!!!!!</td>
    </tr>
  </tbody>
</table>

As you can see, cases 1 and 2 the change is made correctly, but in case 3 no change is made since part of the namespace of the final `app.bar` property has identations..

I am using version 7.22.0
