### ISSUE TITLE
Rewrite-maven: ChangeParentPom recipe does not work correctly with multi-module maven projects

### ISSUE THREAD

**Issue by ferblaca** [openrewrite/rewrite#1753]
I have problems applying the `ChangeParentPom` recipe in multi-module maven projects where the goal is to modify the parent version of the root module of type `pom`.

It seems that the problem is related to the number of modules the maven project contains...

For example, I have created a Recipe in the following [project ](https://github.com/ferblaca/OpenRewriteRecipe) with the goal of modifying the Spring Boot parent to version 2.6.7:

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ChangeParentPomExample
displayName: Change Maven Parent Pom example
recipeList:
  - org.openrewrite.maven.ChangeParentPom:
      oldGroupId: org.springframework.boot
      newGroupId: org.springframework.boot
      oldArtifactId: spring-boot-starter-parent
      newArtifactId: spring-boot-starter-parent
      newVersion: 2.6.7
      versionPattern:
      allowVersionDowngrades: false
```

And on the other hand, I have a [demo project](https://github.com/ferblaca/OpenRewriteDemo) with the rewrite plugin configured for the above active recipe which contains 6 modules, whose [pom.xml](https://github.com/ferblaca/OpenRewriteDemo/blob/main/pom.xml) of type `pom` has Spring Boot parent version 2.6.5 configured. When running `mvn rewrite:run` the expected result is to update the Spring-boot parent version to `2.6.7`, but this is not the case.

Only when I run the command with -N (`mvn rewrite:run -N`) or comment out all or most of the [modules](https://github.com/ferblaca/OpenRewriteDemo/blob/main/pom.xml#L21-L26), the recipe correctly updates the Spring Boot parent version to `2.6.7`.

Can you check it? thank you very much.
