### ISSUE TITLE
MergeYaml inserts mappings with the flow-style format

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#1763]
Discovered in rewrite-kubernetes  [AddConfigurationTest](https://github.com/openrewrite/rewrite-kubernetes/blob/main/src/test/kotlin/org/openrewrite/kubernetes/AddConfigurationTest.kt)

expected: 
```YAML
  spec:
    containers:
    - name: nginx
      image: nginx
      securityContext:
        allowPrivilegeEscalation: false
```
 but was:
```YAML 
  spec:
    containers:
    - name: nginx
      image: nginx
      securityContext: {
        allowPrivilegeEscalation: false}
```
https://github.com/openrewrite/rewrite-kubernetes/actions/runs/2277333955
