### ISSUE TITLE
Environment does not preserve recipeList order for recipes which must be assembled from multiple ResourceLoaders

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1789]
It used to be that recipe execution order wasn't particularly important. Any recipe making a change would result in an additional cycle. But now there wont be another cycle unless a recipe both makes a change and returns `true` from `causesAnotherCycle()`.

So it can be important for a recipe list to be in a particular order. Say, a migration from library A version 1.0 -> 1.1, and from 1.1 -> 1.2. If the "1.0 -> 1.1" part does not run before the "1.1 -> 1.2" part, you might get only the first part of the migration run in a single execution. 

Which brings us to the bug: `YamlResourceLoader` loads recipes that accept parameters separately from recipes which do not accept parameters. Recipes that accept no parameters will end up ordered before recipes that accept parameters in the final recipe list.

**Comment by nmck257** [comment]
> Recipes that accept no parameters will end up ordered before recipes that accept parameters in the final recipe list.

I'm actually seeing the opposite -- recipes w/ params go first. But in either order, agreed, still a bug :)

**Comment by traceyyoshima** [comment]
I think there may be a slight misunderstanding unless something has changed.

We've known for a while that the YamlResourceLoader reorders declarative recipes, but the expectation was that a composite recipe will run until there are no changes. (which as @nmck257  found is not true)

AFAIK, declarative recipes are meant to run without an expectation the recipes are run in order.

So, a declarative recipe should be able to declare recipes in any order:
```yaml
recipeList:
    - Change name from SecondRun to ThirdRun
    - Change name from FirstRun to SecondRun
```

Rather than preserving the `recipeList` order, I think we need to add conditions to check for a CompositeRecipe that has made changes.
Additionally, Sam observed that CompositeRecipes do not check if a recipe one of the declared recipes causes another cycle.

**Comment by nmck257** [comment]
Sounds like we all agree on a change for `CompositeRecipe` propagating the "cause another cycle" flag from its members. @traceyyoshima 

But regarding execution order:

From an outside perspective, I think many users would instinctively expect the order to be preserved (yes it's a "declarative" recipe but it's also being presented as a list), and running the recipes in defined order could shortcut out the need for another cycle, which feels (as a layperson) like a desirable performance improvement.

Consider a sample like this, following a pattern similar to spring framework upgrade recipes:

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.sample.framework.upgrade_3_0
displayName: Upgrade a fake framework to version 3.0
recipeList:
  - org.openrewrite.maven.UpgradeParentVersion:
      groupId: org.sample.framework
      artifactId: framework-parent
      newVersion: 3.0.0
  - com.sample.framework.upgrade_2_0
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: com.sample.library
      oldArtifactId: better-artifact
      newGroupId: com.sample.library
      newArtifactId: best-artifact
---
type: specs.openrewrite.org/v1beta/recipe
name: com.sample.framework.upgrade_2_0
displayName: Upgrade a fake framework to version 2.0
recipeList:
  - org.openrewrite.maven.UpgradeParentVersion:
      groupId: org.sample.framework
      artifactId: framework-parent
      newVersion: 2.0.0
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: com.sample.library
      oldArtifactId: original-artifact
      newGroupId: com.sample.library
      newArtifactId: better-artifact
```
When running `...upgrade_3_0` with the current ordering logic, the artifact rename from `better` to `best` will happen before `...upgrade_2_0` (and therefore the artifact rename from `original` to `better`). And if I'm reading the codebase correctly, then even with the `CompositeRecipe` change, this recipe *won't know* to prompt another cycle: neither `UpgradeParentVersion` nor `ChangeDependencyGroupIdAndArtifactId` set that `causesAnotherCycle` flag, and there's not an option to define that flag on a declarative recipe. So, this recipe would run in one cycle and fail to migrate all the way to `best-artifact`.

And from my limited experience, the recipe reordering seems to be mainly a quirk of the `YamlResourceLoader` / `lazyNext` implementation, and not an intentional optimization with defined benefits.

So, my conclusion would be to preserve the order.

**Comment by traceyyoshima** [comment]
> From an outside perspective, I think many users would instinctively expect the order to be preserved (yes it's a "declarative" recipe but it's also being presented as a list)

I agree with you. Others on the team, several users, and I have brought this up in the past.
But Sam and I will bring it up again.

In terms of migrations like SpringUpgrades we typically wrap declared recipes.

```yaml 
---
# Wraps the 2.3 migration so that it may be called without running the entire migration.
# And adds details about the intent via the display name and description.
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_3
displayName: Upgrade to Spring Boot 2.3
description: 'Upgrade to Spring Boot 2.3 from any prior 2.x version.'
recipeList:
  # The 2.2 upgrade will run first.
  - org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_2

  # The order of dependency changes doesn't effect the API changes.
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: org.springframework.boot
      artifactId: "*"
      newVersion: 2.3.x
      overrideManagedVersion: true
  - org.openrewrite.maven.UpgradeParentVersion:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-parent
      newVersion: 2.3.x

  # Update APIs
  - org.openrewrite.java.spring.boot2.MigrateRestClientBuilderCustomizerPackageName
  - org.openrewrite.java.spring.boot2.MigrateErrorPropertiesIncludeStackTraceConstants
  - org.openrewrite.java.spring.boot2.GetErrorAttributes

---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot2.MigrateRestClientBuilderCustomizerPackageName
displayName: Use `RestClientBuilderCustomizer`
description: '`org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientBuilderCustomizer` was deprecated in 2.3.'
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientBuilderCustomizer
      newFullyQualifiedTypeName: org.springframework.boot.autoconfigure.elasticsearch.RestClientBuilderCustomizer
```

In the provided example:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.sample.framework.upgrade_3_0
displayName: Upgrade a fake framework to version 3.0
recipeList:
  - org.recipe.UpgradeTo3_0
  - com.sample.framework.upgrade_2_0
  - org.recipe.MigrateFromOldLibraryToNewLibrary

---
declare org.recipe.UpgradeTo3_0
---
declare com.sample.framework.upgrade_2_0
---
declare org.recipe.MigrateFromOldLibraryToNewLibrary
```

**Comment by nmck257** [comment]
@traceyyoshima - yep, wrapping the recipes seems like the tidiest workaround. Order is preserved amongst declarative or imperative recipes in the list, and wrapping lets you "recast" an imperative invocation as declarative.

And actually, in your annotated Spring Boot recipe:
```yml
recipeList:
  # The 2.2 upgrade will run first.
  - org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_2

  # The order of dependency changes doesn't affect the API changes.
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: org.springframework.boot
      artifactId: "*"
# ...
```
I believe the 2_2 upgrade technically won't run first, as the dependency changes (being imperative) will pre-empt them in parsing. But in to your point, the dependency changes don't affect the API changes in this case, so it seems to be the same outcome.

Interested to hear what comes next,
