### ISSUE TITLE
ChangeType should also change the source path and constructors when modifying the class definition

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#1904]
The ChangeType recipe should also rename the source file and any constructors when it modifies the class definition (the `ignoreDefinition` is `false`) and the Class is the first, top-level class of a compilation unit.

As an example: 

Given the recipe: 

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.RenameSomething:
  - org.openrewrite.java.ChangeType
      oldFullyQualifiedTypeName: com.example.OldClass
      newFullQualfiedTypeName: org.example.NewClass
```

The expectation would be for the SourceFile to have a modified path of `org.exampl.NewClass.java`
