### ISSUE TITLE
How to change types of different versions of a library

### ISSUE THREAD

**Issue by rbosse** [openrewrite/rewrite#2]
Hi,

We are migration from different versions of Spring Boot.  I would like to be able to change type 
org.springframework.boot.web.support.SpringBootServletInitializer
to
org.springframework.boot.web.servlet.support.SpringBootServletInitializer

(From Spring Boot 1.5 to Spring Boot 2.2).

Is it possible to do that ?

Thanks

**Comment by jkschneider** [comment]
The `org.openrewrite.java.ChangeType` visitor doesn't require both types to be on the classpath to accomplish the change, just preferably the version of the module from which the type is being changed.

This rule can be written declaratively and included in a `META-INF/rewrite/rewrite.yml` as follows:

```yml
---
type: beta.openrewrite.org/v1/visitor
name: org.openrewrite.spring.SpringBootServletInitializerPackage

visitors:
  - org.openrewrite.java.ChangeType:
      type: org.springframework.boot.web.support.SpringBootServletInitializer
      targetType: org.springframework.boot.web.servlet.support.SpringBootServletInitializer
```
