### ISSUE TITLE
Buggy ChangePropertyKey (yaml) when keys have common substring

### ISSUE THREAD

**Issue by sanagaraj-pivotal** [openrewrite/rewrite#2016]
**Recipe**:
```yaml
org.openrewrite.yaml.ChangePropertyKey:
  oldPropertyKey: spring.elasticsearch.rest.sniffer.interval
  newPropertyKey: spring.elasticsearch.restclient.sniffer.interval
```
**Input**:
```yaml
spring:
  elasticsearch:
    rest:
      sniffer:
        interval: 1
```
**current output**:
```yaml
spring:
    elasticsearch:
      rest:
          lient.sniffer.interval: 1
``` 

rest and restclient share substring that begins with rest, this causes the above erroneous output

**correct output should be**:

```yaml
spring:
  elasticsearch:
      restclient.sniffer.interval: 1
```
