### ISSUE TITLE
Maven: AddPlugin - support an option to only place it in the parent POM.

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite#2064]
I have a multi-module project and I wanted to added a Plugin, but when I ran it the plugin was added to each and every POM file and not just the parent one.

Ideally there were be an option to only place it in the parent and not each modules `build` section.

Here's the `rewrite.yml` that I created.

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.difrango.AddSortPom
displayName: Add in the sortpom (https://github.com/Ekryd/sortpom) plugin.
recipeList:
  - org.openrewrite.maven.AddPlugin:
      groupId: com.github.ekryd.sortpom
      artifactId: sortpom-maven-plugin
      version: latest.release
      configuration: <configuration> <predefinedSortOrder>custom_1</predefinedSortOrder> <lineSeparator>\n</lineSeparator> <encoding>${project.build.sourceEncoding}</encoding> <nrOfIndentSpace>4</nrOfIndentSpace> <sortProperties>true</sortProperties> <sortDependencies>scope,groupId,artifactId</sortDependencies> </configuration>
      executions: <executions> <execution> <goals> <goal>sort</goal> </goals> <phase>verify</phase> </execution> </executions>
```
