### ISSUE TITLE
Error writing Maven-POM with special characters

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#2189]
Hi,

executing a recipe that changes the POM leads to incorrect changes in text that contains special characters.

Take the following example, which leads to `<description>Some Example#39;</description>`:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <version>1.0.0-SNAPSHOT</version>
    <artifactId>example</artifactId>
    <packaging>jar</packaging>

    <name>Some Exmple</name>
    <description>Some &#39;Example&#39;</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies />

</project>
```

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.example.recipe
displayName: org.example.recipe
description: org.example.recipe
recipeList:
  - org.openrewrite.maven.AddProperty:
      key: maven.compiler.release
      value: 17
      preserveExistingValue: false
```

Thanks and kind regards
Thomas
