### ISSUE TITLE
MergeYamlVisitor - inline comments not taken into account

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#2218]
Hi,

the `MergeYamlVisitor` does not take inline comments into account at merging YAMLs. See the test:

```kotlin
@Test
fun existingEntryBlockWithComment() = assertChanged(
    recipe = MergeYaml(
        "$",
        """
            spring:
              application:
                description: a description
        """.trimIndent(),
        false,
        null
    ),
    before = """
        spring:
          application:
            name: main #Some comment
    """,
    after = """
        spring:
          application:
            name: main #Some comment
            description: a description
    """
)
```

The actual result is:
```yaml
spring:
  application:
    name: main
    description: a description #Some comment
```

Thanks and kind regards
Thomas
