### ISSUE TITLE
FindDepricated recipes required parameter validation

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#2321]
FindDeprecated classes, types and methods recipes are not validating the options resulting in recipe errors

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: MyCustomRecipe
displayName: My custom recipe
description: Find deprecated things.
recipeList:
  - org.openrewrite.java.search.FindDeprecatedMethods:
      methodPattern: " *(..)"
  - org.openrewrite.java.search.FindDeprecatedClasses: {}
  - org.openrewrite.java.search.FindDeprecatedFields: {}
```

![image](https://user-images.githubusercontent.com/22326988/196769516-5f98b81b-2598-43d2-a44c-00ffb5f16f5a.png)
