### ISSUE TITLE
Properties ChangePropertyKey replaces "###############" by "#"

### ISSUE THREAD

**Issue by ge0ffrey** [openrewrite/rewrite#2411]
I ran this recipe

```
recipeList:
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: optaplanner.solver.solve-length
      newPropertyKey: optaplanner.solver.solve.duration
```

on this application.properties file

```
########################
# Demo properties
########################

quarkus.optaplanner.solver.solve-length=foo
```
and got this
```
#
# Demo properties
#

quarkus.optaplanner.solver.solve.duration=foo
```

It did content (code style?) changes that it shouldn't have.
