### ISSUE TITLE
The ReplaceConstant recipe does not work correctly.

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#2458]
Good afternoon, I am having trouble using the **ReplaceConstant** recipe. When trying to change a constant to a literal with the latest released version of plugin (**4.37.0**):

```
###################################################################################################
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ReplaceConstantExample
displayName: Replace constant with literal value example
recipeList:
  - org.openrewrite.java.ReplaceConstant:
      owningType: com.test.project.interceptor.InterceptorsFactory
      constantName: USER_NAME_VALID_VALUE
      literalValue: UsernameToken
```

I get always the same error:

```
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.37.0:dryRun (default-cli) on project test-project: A type incompatibility occurred while executing org.openrewrite.maven:rewrite-maven-plugin:4.37.0:dryRun:
 class org.openrewrite.java.tree.J$Identifier cannot be cast to class org.openrewrite.java.tree.J$Literal (org.openrewrite.java.tree.J$Identifier and org.openrewrite.java.tree.J$Literal are in unnamed module of loader org.codehaus.p
lexus.classworlds.realm.ClassRealm @4b862408)
```
![image](https://user-images.githubusercontent.com/92039871/204315005-15af51bc-7016-458a-a0b4-af199d3f1fe1.png)

I have tried with other lower versions of the plugin **4.36.0** to **4.24.0**, but it still fails, and the error I get is:

`[WARNING] java.lang.IllegalArgumentException: Unknown literal type for literal value: UsernameToken`
```
diff --git a/src/main/java/com/test/project/web/HelloController.java b/src/main/java/com/test/project/web/HelloController.java
index 775cad2..6ccde32 100644
--- a/src/main/java/com/test/project/web/HelloController.java
+++ b/src/main/java/com/test/project/web/HelloController.java
@@ -4,7 +4,17 @@ org.openrewrite.java.ReplaceConstant
 
 public class HelloController {
 
-	String var1 = InterceptorsFactory.USER_NAME_VALID_VALUE;
+	String var1 = /*~~(Recipe failed with an exception.
+java.lang.IllegalArgumentException: Unknown literal type for literal value: UsernameToken
+  org.openrewrite.java.ReplaceConstant$1.buildLiteral(ReplaceConstant.java:114)
+  org.openrewrite.java.ReplaceConstant$1.visitFieldAccess(ReplaceConstant.java:62)
+  org.openrewrite.java.ReplaceConstant$1.visitFieldAccess(ReplaceConstant.java:57)
+  org.openrewrite.java.tree.J$FieldAccess.acceptJava(J.java:1858)
+  org.openrewrite.java.tree.J.accept(J.java:63)
+  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:277)
+  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
+  org.openrewrite.java.JavaVisitor.visitLeftPadded(JavaVisitor.java:1292)
+  ...)~~>*/InterceptorsFactory.USER_NAME_VALID_VALUE;
```
Please can you tell me what might be happening or if I am doing something wrong.

Attached is an example project: https://github.com/josemariavillar/test_project/tree/replace-constant

There is another issue that was opened some time ago with the same problem and it is supposedly solved and closed. I attach it in case it can help you: https://github.com/openrewrite/rewrite/issues/1752

**Comment by josemariavillar** [comment]
https://github.com/openrewrite/rewrite/issues/1752

**Comment by knutwannheden** [comment]
Looks like I broke this with #2422. Possibly there should be a special case for strings, as it would be weird to require quoting the string literals in the YAML config.

**Comment by knutwannheden** [comment]
@josemariavillar If you add double quotes to the literal value, it should work. Something like:
```yaml
  - org.openrewrite.java.ReplaceConstant:
      owningType: com.test.project.interceptor.InterceptorsFactory
      constantName: USER_NAME_VALID_VALUE
      literalValue: '"UsernameToken"'
```

@pway99 Looking at the code I am slightly surprised this apparently worked before. I will try to debug it and see why that was the case and if there is anything we can reasonably do about it. Possibly the YAML literal's type could be used, so that if it is a string then also make an attempt with added double quotes around the value. But I assume that at the point the recipe has been created, this info will have been lost.
