### ISSUE TITLE
ChangeValue for YAML files does not support arrays

### ISSUE THREAD

**Issue by JetteBke** [openrewrite/rewrite#2595]
Hello everybody,

I have faced the following issue, where a list item in a yaml file (Helm Chart) does not get replaced with the org.openrewrite.yaml.ChangeValue recipe.

My rewrite.yml
```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.myorg.ChangeHelmYamlValues
displayName: Change helm charts yaml value
recipeList:
  - org.openrewrite.yaml.ChangeValue:
      oldKeyPath: $.sources[0]
      value: https://super-cool-url.git
  - org.openrewrite.yaml.ChangeValue:
      oldKeyPath: $.maintainers[0].name
      value: Lisa
```
      
      
The Chart.yaml
```
sources:
    - https://old-url.git
maintainers:
    -  name: Mara
        email: mara@mara.com
```

When I run openrewrite it replaces the name but not the url.

Other options I tried for the `oldKeyPath`
- `$.sources` (results in `sources:nullhttps://super-cool-url.git`)
- `$.sources[0].[?(@ == 'https://old-url.git')]` (does nothing)
- `$.sources[0].` (does nothing)

Let me know if more info is needed.
Thanks,
Jette
