### ISSUE TITLE
ChangeDependencyGroupIdAndArtifactId leads to `No version provided` for parent managed dependency versions

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#2691]
Uncovered through https://github.com/openrewrite/rewrite-spring/pull/277; when changing the groupId & artifactId there with
```yaml
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: mysql
      oldArtifactId: mysql-connector-java
      newGroupId: com.mysql
      newArtifactId: mysql-connector-j
      newVersion: 8.0.x
```
We get an error `No version provided` when the version was managed by the parent, even though the parent is also updated in `UpgradeSpringBoot_2_7`.
```xml
<project>
        <modelVersion>4.0.0</modelVersion>
        <groupId>com.example</groupId>
        <artifactId>demo</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <parent>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-parent</artifactId>
          <version>2.7.8</version>
          <relativePath/> <!-- lookup parent from repository -->
        </parent>
        <dependencies>
          <!--~~(No version provided)~~>--><dependency>
             <groupId>com.mysql</groupId>
             <artifactId>mysql-connector-j</artifactId>
             <scope>runtime</scope>
          </dependency>
        </dependencies>
      </project>
```
