### ISSUE TITLE
Add Gradle Enterprise plugin recipe should allow configuration

### ISSUE THREAD

**Issue by alextu** [openrewrite/rewrite#2697]
Add/Update the Gradle Enterprise plugin should allow configuring, here's a minimal configuration example:
https://github.com/gradle/gradle-enterprise-build-config-samples/blob/main/common-gradle-enterprise-gradle-configuration-groovy/settings.gradle#L8-L17

Here are all the possible attributes
https://docs.gradle.com/enterprise/gradle-plugin/api/com/gradle/enterprise/gradleplugin/GradleEnterpriseExtension.html

For a start, we suggest to add as configuration attribute with only a few attributes for a start :
- `server` (mandatory): URL to the GE server
- `allowUntrustedServer` (optional), not set by default

Also the `publishAlways()` and `uploadInBackground = false` should always be set, see example below

So given,
```
 - org.openrewrite.gradle.plugins.AddGradleEnterprise:
     version: 3.12.4
     configuration:
       server: https://foo
       allowUntrustedServer: true
```
It would output apply/change the Gradle configuration to
```
gradleEnterprise {
    server = 'https://foo' 
    allowUntrustedServer = true
    buildScan {
        publishAlways()
        uploadInBackground = false
    }
}
```
