### ISSUE TITLE
Yaml applicability tests should be evaluated once before running recipes in the list, are actually evaluated once per recipe in the list

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2711]
Thanks to @shanman190 for discovering and reporting this as part of https://github.com/openrewrite/rewrite/pull/2676/files#

Currently yaml recipes with applicability tests aren't working right. The applicability test is being checked before each recipe in the recipe list, rather than once for the whole list. This can lead to unexpected results.

This yaml recipe can reproduce the problem when applied to a plain text file containing the text "1":
```yaml
          ---
          type: specs.openrewrite.org/v1beta/recipe
          name: org.openrewrite.ApplicabilityExactlyOnce
          displayName: Applicability test runs once for the whole recipe list
          description: >
            An applicability test should be run once and if a match is found, all recipes in the list should be run.
            So if one of the recipes in the list makes a change which would cause the applicability test to no longer match,
            subsequent recipes in the list should still execute.
            
            Given a text file containing the number "1", running this recipe should result in a file which contains "3".
            If the applicability test is incorrectly applied to individual recipes in the list, the (incorrect) result would be "2".
          applicability:
            anySource:
              - org.openrewrite.text.FindAndReplace:
                  find: "1"
                  replace: "Applicable"
          recipeList:
            - org.openrewrite.text.ChangeText:
                  toText: "2"
            - org.openrewrite.text.ChangeText:
                  toText: "3"
```
