### ISSUE TITLE
Yaml recipes in the list should not be run if single source applicability tests failed

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite#2754]
Thanks @shanman190 for discovering and reporting this as part of https://github.com/openrewrite/rewrite/issues/2746

this issue only happened with recipes that have the `visit(List<SourceFile> before, ExecutionContext ctx)` method overridden.

A recipe has two different ways to run.
- 1. Override `getVisitor()` method, and invoke `getVisitor().visit(@Nullable Tree tree, P p)` to transform a single file.
- 2. Override `visit(List<SourceFile> before, ExecutionContext ctx)` method, and invoke it to transform multiple files.
Typically, for a recipe, only one of the two methods mentioned above is required to be overridden.
The recipe scheduler invokes both methods in different places in the flow, all recipes in the list should not be run only when the applicability test fail.

This yaml recipe can reproduce the problem when applied to a plain text file containing the text "2", expected to have no change.

```yaml
          ---
          type: specs.openrewrite.org/v1beta/recipe
          name: org.openrewrite.RecipesToTransformMultiFiles
          displayName: Recipes in the list which override 'visit()' method should not be run if applicability test fail
          description: >
            A recipe has two different ways to run.
            1. Override 'getVisitor()' method, and invoke `getVisitor().visit(@Nullable Tree tree, P p)` to transform a single file.
            2. Override `visit(List<SourceFile> before, ExecutionContext ctx)` method, and invoke it to transform multiple files.
            Typically, for a recipe, only one of the two methods mentioned above is required to be overridden.
            The recipe scheduler invokes both methods in different places in the flow, this test is intended to make sure 
            those recipes that overrides 'visit()' method can be run correctly with the applicability test.
            
            All recipes in the list should not be run only when the applicability test fail.
            
            Given a text file containing the number "2", running this recipe should result with no change.
          applicability:
            singleSource:
              - org.openrewrite.text.FindAndReplace:
                  find: "1"
                  replace: "A"
          recipeList:
            - org.openrewrite.text.AppendToTextFile:
                  relativeFileName: "file.txt"
                  content: "->2"
                  preamble: "preamble"
                  appendNewline : false
                  existingFileStrategy: "continue"
            - org.openrewrite.text.AppendToTextFile:
                  relativeFileName: "file.txt"
                  content: "->3"
                  preamble: "preamble"
                  appendNewline : false
                  existingFileStrategy: "continue"
```
