### ISSUE TITLE
Standardize nullability annotations

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#2838]
There's no shortage of nullability annotations; we even have our own, which are [not always consistently applied](https://github.com/openrewrite/rewrite/pull/2835).
Lombok has a decent [list of mostly-interchangeable nullability annotations](https://github.com/projectlombok/lombok/blob/v1.18.26/src/core/lombok/core/configuration/NullAnnotationLibrary.java#L64), although they are [missing Jakarta](https://github.com/projectlombok/lombok/pull/3350) & OpenRewrite.
And while we already have the ChangeType recipe to switch these over individually, it might make sense to have a configurable dedicated recipe to switch between implementations.

non-null | nullable
-- | --
javax.annotation.Nonnull | javax.annotation.Nullable
jakarta.annotation.Nonnull | jakarta.annotation.Nullable
org.eclipse.jdt.annotation.NonNull | org.eclipse.jdt.annotation.Nullable
org.jetbrains.annotations.NotNull | org.jetbrains.annotations.Nullable
org.netbeans.api.annotations.common.NonNull | org.netbeans.api.annotations.common.NullAllowed
androidx.annotation.NonNull | androidx.annotation.Nullable
android.support.annotation.NonNull | android.support.annotation.Nullable
org.checkerframework.checker.nullness.qual.NonNull | org.checkerframework.checker.nullness.qual.Nullable
edu.umd.cs.findbugs.annotations.NonNull | edu.umd.cs.findbugs.annotations.Nullable
org.springframework.lang.NonNull | org.springframework.lang.Nullable
org.jmlspecs.annotation.NonNull | org.jmlspecs.annotation.Nullable
org.openrewrite.internal.lang.NonNull | org.openrewrite.internal.lang.Nullable

**Comment by AlexanderSkrock** [comment]
I would like to take on this one.

**Comment by timtebeek** [comment]
Great to hear! I think in the past we'd discussed to maybe add parameters to declarative yaml recipes, which could be a good fit here, although I can't find that issue right now. Likely best tackled separately and out of scope for this one.

In this case an imperative Java recipe that merely calls out a bunch of ChangeType recipes could already help a lot, potentially aided by some applicability checks on whether the corresponding dependency containing the target annotation is available, and/or add required dependency if needed. Not all aspects have been thought through fully yet, but curious to hear your thoughts on these!

**Comment by timtebeek** [comment]
Thank for the detailed analysis! Here's a reply to your questions at the top:

> What do you mean by parameters for declarative recipes. the variables annotated with @Option?

So with declarative recipes I mean the [yaml format to configure recipes](https://docs.openrewrite.org/reference/yaml-format-reference). We've discussed in the past to potentially add parameters to recipes purely defined in yaml, but have not gotten around to that yet. This could have been an approach for this recipe: only define the recipe in yaml as taking two options, and apply a list of ChangeType recipes that way.

Defining recipes purely in Yaml is limited though, and might not have worked all the way through with some of the checks that we want to do on availability of annotations and adding dependencies where necessary. I suggest we stick to a Java recipe here for now, which [links together other known recipes](https://docs.openrewrite.org/concepts-and-explanations/recipes#linking-recipes-together). That keeps the logic out of the implementation as much as possible, and allows us to potentially revisit this as a yaml only recipe in the future.

> Does ChangeType also support replacing usage of types as Annotations? If that is possible we would not need another recipe. Later in my comment, I thought about implementing a ReplaceAnnation recipe ,which would not be necessary anymore.

[`ChangeType`](https://docs.openrewrite.org/reference/recipes/java/changetype) does indeed support swapping one annotation for another; here is [an example in rewrite-spring](https://github.com/openrewrite/rewrite-spring/blob/07053ffe1739ea3af769fd87e0e7d849611fbdf1/src/main/resources/META-INF/rewrite/spring-boot-27.yml#L42-L44). So for anyone using a homegrown nullable annotation, I'd suggest they first run a `ChangeType` themselves, before running this recipe to standardize other known annotations onto a single pair of annotations. 

That removes the need for any specific `ReplaceAnnotation` recipe, or `additionalNullableAnnotations` / `additionalNonNullAnnotations` options, making this recipe easier to implement.

> Thoughts on annotations and their dependencies

I think it's fine to add the latest version of the corresponding dependency, only if using the annotations, and not already available transitively. Both of these restrictions are options of using [Add dependency](https://docs.openrewrite.org/reference/recipes/maven/adddependency).

--- 

## General suggestion

I think this implementation would work best as a Java recipe that takes two options, as you've sketched already, and then replaces a suite of known alternative nullability annotations. This Java recipe can then be used a number of times from yaml to define a couple of suggested recipes that people can run without further configuration. For example:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.nullability.UseJavaxNullabilityAnnotations
displayName: Use javax nullability annotations
description: Replace other well known Java nullability annotations with javax.
recipeList:
  - org.openrewrite.java.nullability.StandardizeNullabililtyAnnotations
      nullableAnnotation: javax.annotation.Nullable
      nonNullAnnotation: javax.annotation.Nonnull
  - org.openrewrite.maven.AddDependency:
      groupId: javax.annotation
      artifactId: javax.annotation-api
      version: 1.x
      onlyIfUsing: javax.annotation.*
      acceptTransitive: "True"
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.nullability.UseJakartaNullabilityAnnotations
displayName: Use jakarta nullability annotations
description: Replace other well known Java nullability annotations with jakarta.
recipeList:
  - org.openrewrite.java.nullability.StandardizeNullabililtyAnnotations
      nullableAnnotation: jakarta.annotation.Nullable
      nonNullAnnotation: jakarta.annotation.Nonnull
  - org.openrewrite.maven.AddDependency:
      groupId: jakarta.annotation
      artifactId: jakarta.annotation-api
      version: 2.x
      onlyIfUsing: jakarta.annotation.*
      acceptTransitive: "True"
---
...
```

**Comment by AlexanderSkrock** [comment]
Thank you for your extensive response and also some useful links!

Having the already existent recipes `ChangeType` and `AddDependency`, we will barely have any additional logic to implement exception for validations. Pretty charming!

I am a fan of your ready-to-use recipes, thank you for these. Should I embed them somewhere as documentation or did you think of eample implementations, which can directly be used?

One last thought on your example recipes. I think we would either have to integrate the AddDependency recipe as sub recipe inside `StandardizeNullabililtyAnnotations` or swap the order and potentially remove `onlyIfUsing: xxx`. My concern, is that either `StandardizeNullabililtyAnnotations` already adds the latest version before `AddDependency` ran or `AddDependency` runs before `StandardizeNullabililtyAnnotations` but these annotations are not yet, and in consequence the dependency will not be added.

I could think of following:
- Refrain on auto-adding the neccessary dependency inside `StandardizeNullabililtyAnnotations` and only check if the annotation is available, possibly giving a hint on the necessary dependency
- Implement read-to-use recipes as you already commented:
```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.nullability.UseJakartaNullabilityAnnotations
displayName: Use jakarta nullability annotations
description: Replace other well known Java nullability annotations with jakarta.
recipeList:
    - org.openrewrite.maven.AddDependency:
      groupId: jakarta.annotation
      artifactId: jakarta.annotation-api
      version: 2.x
      onlyIfUsing: jakarta.annotation.*
      acceptTransitive: "True"
  - org.openrewrite.java.nullability.StandardizeNullabililtyAnnotations
      nullableAnnotation: jakarta.annotation.Nullable
      nonNullAnnotation: jakarta.annotation.Nonnull
```
(This would required us to constantly update the version as new versions are released.)

Advantages are, these are easy-to-use, zero configuraton and allow to switch between annotations as easy as changing the recipe name.
As downside, if the recipe `StandardizeNullabililtyAnnotations` is used aside the preconfigured recipes, users would probably need to an `AddDependency` recipe manually because they are tightly coupled or manually change dependencies. Anyway, this seems okay to me.

**Comment by timtebeek** [comment]
> Should I embed them somewhere as documentation or did you think of example implementations, which can directly be used?

I think the ready to use preconfigured recipes can go into a new file in this folder:
https://github.com/openrewrite/rewrite/tree/main/rewrite-java/src/main/resources/META-INF/rewrite
We already have a number of recipes there that are no more than a combination of existing recipes.
By providing these ready made recipes we ensure people are able to easily target a pair of annotations.

We can play around with the required order of the AddDependency versus ChangeType once we have a suite of tests, optionally [using for instance `mavenProject`](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite%20mavenProject&type=code) to verify that we add the required dependency only when necessary. The reason I put it last was because I would not want us to add any dependency when we don't use any nullability annotations in a project (yet), but that could maybe also be achieved with an applicability test.

> This would required us to constantly update the version as new versions are released.

There would be no need to update the dependency version when we use [dependency version selectors](https://docs.openrewrite.org/reference/dependency-version-selectors#xrange). I wasn't explicit about this earlier, but `2.x` actually does work by itself, and was not a placeholder for a particular version. :)

**Comment by AlexanderSkrock** [comment]
Basically I was done with the initial implementation, just missing some more preconfigured recipes for the various frameworks. While thinking about more specific annotation, I realized the replacement of nullability annotations might be slightly more complex than I initially thought.

**So, what's the problem:**
There are some annotations that can be defined in a higher level, e. g. on a `class` or a `package`. Some might be applicable on those in addition to `methods` or `fields`, but some may not be. A possible example would be `org.openrewrite.internal.lang.NonNullApi` which is not applicable on all element types. For example Javax annotations have no limitations on their annotations, but rewrite's own or lombok do have.
Furthermore, there is an additional problem. The scope of afore mentioned example `NonNullApi` is only methods including their parameters and return values.
=> When, having one of these edge cases, a simple replacement is not possible. Further, it might break code.

**A possible approach**
We could define all known nullability annotations as follows:
```java
private static final Set<NullabilityAnnotation> KNOWN_NULLABILITY_ANNOTATIONS = Stream.of(
        nullable("javax.annotation.Nullable").withAllTargets().withScopes(),
        nonNull("javax.annotation.Nonnull").withAllTargets().withScopes(),

        nullable("org.openrewrite.internal.lang.Nullable").withAllTargets().withAllScopes(),
        nullable("org.openrewrite.internal.lang.NullFields").withTargets(ElementType.PACKAGE, ElementType.TYPE).withScopes(ElementType.FIELD),
        nonNull("org.openrewrite.internal.lang.NonNull").withAllTargets().withAllScopes(),
        nonNull("org.openrewrite.internal.lang.NonNullFields").withTargets(ElementType.PACKAGE, ElementType.TYPE).withScopes(ElementType.FIELD),
        nonNull("org.openrewrite.internal.lang.NonNullApi").withTargets(ElementType.PACKAGE, ElementType.TYPE).withScopes(ElementType.METHOD, ElementType.PARAMETER)
).collect(Collectors.toSet());
```
Also we would change the api and allow multiple nullable and not-null annotations to be configured:
```java
@Option(displayName = "Nullable annotations to use",
        description = "All other nullable annotations will be replaced by this one.",
        example = "javax.annotation.Nullable")
List<NullabilityAnnotation> nullableAnnotations;

@Option(displayName = "Non-null annotations to use",
        description = "All other non-null annotations will be replaced by this one.",
        example = "javax.annotation.Nonnull")
List<NullabilityAnnotation> nonNullAnnotations;
```
For example our `UseJavaxNullabilityAnnotations` recipe would change as follows:
````yml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.maven.java.UseJavaxNullabilityAnnotations
displayName: Use javax nullability annotations
description: Replace other well known Java nullability annotations with javax.
recipeList:
  - org.openrewrite.java.StandardizeNullabilityAnnotations:
      nullableAnnotations:
        - fqn: javax.annotation.Nullable
      nonNullAnnotations:
        - fqn: javax.annotation.Nonnull
  - org.openrewrite.maven.AddDependency:
      groupId: javax.annotation
      artifactId: javax.annotation-api
      version: 1.x
      onlyIfUsing: javax.annotation.*
      acceptTransitive: "True"
```
For the sake of usability, I would say do not have to define targets and scopes again for annotations that are contained in our known pool of annotations, these will be inserted on the fly. Still, it would be possible to add custom annotations as standardized annotations, by simply by adding those fields. (Only question would remain, regarding migrating away from custom annotations, which would again need another parameters, with the same structure for manually adding known annotations).
When it comes to implementation, it would be a bit more than just chaining a couple `ChangeType` recipes. When ever we approach a nullability annotation, we could lookup a matching annotation with an acceptable target type. For, scopes we could either only 1:1 replacement or splitting/combing 1 in 2. An example could be replacing `@Nonnull` of Javax on class level with `NonNullFields` and `NonNullApi` from rewrite and vice versa. That way, we could make sure the semantics stay the same.

Of course, we could still stick to the minimalistic approach, tho it might not be feature-complete and lead to issues in some edge cases. So, what do you think, @timtebeek ?

Besides, that question, I was not able to successfully run my testcases, because sub recipes were not called. My sub recipes were added, but then skipped. I exaplained it a bit more in detail [here](https://github.com/openrewrite/rewrite/commit/ca24647fd6c88d540db267b78e6f655229ac14b1#r106747421). Could you also have a look on this, @timtebeek . I would really appreciate help on this!

Kind regards
Alexander Skrock
