### ISSUE TITLE
ImportLayoutStyle doesn't work as expected

### ISSUE THREAD

**Issue by tisonkun** [openrewrite/rewrite#2845]
```xml
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>${maven-rewrite-plugin.version}</version>
                <configuration>
                    <activeStyles>
                        <activeStyle>com.netflix.eureka.Style</activeStyle>
                    </activeStyles>
                    <activeRecipes>
                        <activeRecipe>org.openrewrite.java.format.AutoFormat</activeRecipe>
                    </activeRecipes>
                </configuration>
            </plugin>
```

doesn't expand star import after `mvn rewrite:run`:

```java
import io.korandoru.zeronos.core.config.*;
import io.korandoru.zeronos.server.ZeronosServer;
import java.time.Instant;
import java.util.HashMap;
import lombok.Cleanup;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
```

with manually formatted:

```java
import io.korandoru.zeronos.core.config.ClusterConfig;
import io.korandoru.zeronos.core.config.ServerConfig;
import io.korandoru.zeronos.server.ZeronosServer;
import java.time.Instant;
import java.util.HashMap;
import lombok.Cleanup;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
```

**Comment by jacksparrow414** [comment]
Hi Community, I faced the same problem. my configuration is as follows  

maven plugin configuration
```xml
<plugin>  
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <configuration>
        <configLocation>${project.basedir}/../parent/rewrite.yml</configLocation>
        <activeRecipes>
        <recipe>RemoveUnusedImports</recipe>
        </activeRecipes>
        <activeStyles>
        <style>NoStarImports</style>
        </activeStyles>
  </configuration>
  </plugin>
```
rewrite.yml  

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: RemoveUnusedImports
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePatterns: "src/main/java/**/*.java"
recipeList:
  - org.openrewrite.java.RemoveUnusedImports

---
type: specs.openrewrite.org/v1beta/style
name: StarImports
styleConfigs:
  - org.openrewrite.java.style.ImportLayoutStyle:
      classCountToUseStarImport: 9999
```

there are two problems

1st, there are no unused imports in my files, only star imports. after running `mvn rewrite:run`, I found that only some of the star imports of the Java files were eliminated, not all of them.

2nd, I want to exclude Java files under the test directory, so I configured filePatterns, but it does not work. BTW, I tested filePatterns using https://www.digitalocean.com/community/tools/glob
