### ISSUE TITLE
ChangeMethodTargetToStatic recipe does not work with static methods referenced using classes

### ISSUE THREAD

**Issue by srmalkan** [openrewrite/rewrite#2859]
For example ,
Consider class A 
```
package a;
public class A {
   public static void foo() {}
}
```
Consider class B
```
package b;
public class B {
   public static void foo() {}
}
```
And Class C using Class A
```
import static a.A;
class C {
   public void test() {
      // static method referenced using class 
       A.foo();
   }
}
```

Here if we apply **ChangeMethodTargetToStatic("a.A foo()", "b.B")** , it stays as it is.

I am not sure whether it is a limitation of the recipe or [MethodPattern](https://docs.openrewrite.org/reference/method-patterns).

**Comment by timtebeek** [comment]
Had a bit of a look; turns out the issue in #2853 could be resolved by changing the order in which two recipes were applied.

Did uncover a slightly different issue potentially with how method patterns match, as making the following change in the recipe

https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/resources/META-INF/rewrite/java-best-practices.yml#L36

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.cleanup.ReplaceApacheCommonsLang3ValidateNotNullWithObjectsRequireNonNull
displayName: Replace `org.apache.commons.lang3.Validate#notNull` with `Objects#requireNonNull`
description: 'Replace `org.apache.commons.lang3.Validate.notNull(Object)` with `Objects.requireNonNull(Object)`.'
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.apache.commons.lang3.Validate notNull(Object, String)
      newMethodName: requireNonNull
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.apache.commons.lang3.Validate notNull(Object)
      newMethodName: requireNonNull
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.commons.lang3.Validate requireNonNull(..)
      fullyQualifiedTargetTypeName: java.util.Objects
```

Does not match to do the replacement in the following test.
```java
    @Test
    void replaceWithTwoArguments() {
        rewriteRun(
          java(
            """
              import org.apache.commons.lang3.Validate;
              
              class Test {
                  void test(Object obj) {
                      Validate.notNull(obj, "Object should not be null");
                  }
              }
              """,
            """
              import java.util.Objects;
              
              class Test {
                  void test(Object obj) {
                      Objects.requireNonNull(obj, "Object should not be null");
                  }
              }
              """
          )
        );
    }
```
