### ISSUE TITLE
Forced AddDependency recipe

### ISSUE THREAD

**Issue by josetesan** [openrewrite/rewrite#2879]
Hi !

We are using open rewrite maven recipes to upgrade a given project dependencies ( or remove/upgrade them ) with no previous check, because we created an archetype and are updated applications using it to newest versions.

As such, when we add a x.y.z dependency , we use AddDependency recipe to add it to the target pom, but we are finding AddDependency recipe has too many considerations, specially the "OnlyIfUsing" attribute, that maybe should be Nullable.

That will make the AddDependency recipe just relay on the pom.xml, and no java file at all.

Besides, as we are forcing users to use that dependency, we don't care about pom properties or project resolve, so don't see the maven download options useful, as it will imply using a private registry and all the stuff involved ( latency, delays , etc )

My request is that if there could be an AddDependency recipe that could match this requirements, a force changed.

So with RemoveDependency or UpdateDependency.

Thanks.

**Comment by timtebeek** [comment]
hi @josetesan ! Would you mind telling me how you're currently composing and running migration recipes? It's not explicit from your question, but from the description it seems like maybe you're invoking the `AddDependency` recipe from an imperative Java recipe, is that correct?

You might be interested in [running recipes with a Yaml configuration](https://docs.openrewrite.org/running-recipes/getting-started#step-5-run-a-recipe-with-yaml-configuration), especially for the simpler recipes that are typically composed together with other steps. That also allows you to only specify required arguments. Your `rewrite.yml` would come out to something similar to this:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.AddGuava
displayName: Add Guava
description: Adds the Guava Maven dependency
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: com.google.guava
      artifactId: guava
      version: 29.x
```
You can compose & export these recipe definitions as needed through our builder: https://public.moderne.io/recipes/builder, and then optionally place a `rewrite.yml` file in your project root (temporarily), or package them into a migration module through `src/main/resources/META-INF/rewrite`.

You can then run these recipes with a command similar to this:
```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -DactiveRecipes=com.example.AddGuava
```

Does that resolve your immediate need for a simpler way to define recipes with only their relevant arguments?

**Comment by josetesan** [comment]
Hi !
Yes,  we're running a imperative java recipe.
We are building a cli-tool that runs open rewrite recipes programmatically, and that's the way we decided to go : yaml recipes are not the road to go currently.
Are we on a dead-end ?

**Comment by rpau** [comment]
Hi @josetesan , we are building a free use CLI tool that avoid to configure your repositories using open rewrite. This CLI is primary designed to ingest the LSTs to the Moderne platform and run recipes from there at scale without having to rebuild all the repos. 

From your comment, you will end up in the wrong path/direction assuming that you can simply resolve the classpath and run open rewrite (which it fails when there are previous code generation steps) avoiding the build tool configuration because there are so many interdependent build steps.  

I can share more details if you are interested via Slack or a call. I will invite you using your GitHub email address.

**Comment by josetesan** [comment]
Thansk @rpau , I'll talk to you about it !.
However, @timtebeek , I created a sample repo, https://github.com/josetesan/maven-rewrite-test, a as test-bed.
If you run mvn rewrite:run, it yields a NullPointerException.

Looks like something is wrong with this recipe, or at least, how I do interpret it works.

**Comment by timtebeek** [comment]
Hi @josetesan Looks like we arrived at roughly the same conclusion indeed; here's the `rewrite.yml` I ended up using:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.AddGuava
displayName: Add Guava
description: Adds the Guava Maven dependency
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: com.google.guava
      artifactId: guava
      version: 29.x
      versionPattern: '-jre'
      onlyIfUsing: java..*
```
The `versionPattern` is requiered specifically for Guava, so maybe that was not the best example. With that `versionPattern` I do not see the download POM error, and it correctly resolves `29.x` to `29.0-jre`.
