### ISSUE TITLE
org.openrewrite.java.RemoveAnnotation Precondition Question

### ISSUE THREAD

**Issue by chhex** [openrewrite/rewrite#2912]
I am running the org. recipe: 

```
type: specs.openrewrite.org/v1beta/recipe
name: com.example.RemoveAnnotationExample
displayName: Remove annotation example
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@com.example.mapping.ReportObject'
```

The annotation is a so called [Active Annotation](https://www.eclipse.org/xtend/documentation/204_activeannotations.html) , which [Xtend](https://www.eclipse.org/xtend/index.html) uses for Java Code generation. In the generated Code, on which the recipe is applied,  it is purely informational and has no effect.

I have ran several recipes  on the code: 

```
type: specs.openrewrite.org/v1beta/recipe
name: com.mycom.RemoveAnnotationExample
displayName: Remove annotation example
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@com.mycom.mapping.ReportObject'
  - org.openrewrite.java.format.AutoFormat
  - org.openrewrite.java.format.BlankLines
  - org.openrewrite.java.format.RemoveTrailingWhitespace
  - org.openrewrite.java.format.WrappingAndBraces
  - org.openrewrite.java.cleanup.UseJavaStyleArrayDeclarations
  - org.openrewrite.hcl.format.AutoFormat
  - org.openrewrite.java.cleanup.UnnecessaryParentheses
  - org.openrewrite.java.cleanup.RemoveExtraSemicolons 
```

And they work fine, except for the org.openrewrite.java.RemoveAnnotation

I have Java code like: 

```
import com.mycom.mapping.ReportObject;
.....

@ReportObject
public class RoAbwicklungOe {
  private String titel;

  private String vorgabenTitel;

  private String vorgabenText;

  private String vorgabenLink;
....

```

Would expect the @ReportObject to be removed, but it is not. 
Are there preconditions for removing an Annotation or have i misconfigured the Recipe? 
Any hint or feedback very much appreciated

 In the context of this Project where we are migrating  from Xtend to "pure" Java, it seems to us that openrewrite has a great potential and i am testing currently different usage scenarios

**Comment by timtebeek** [comment]
Typically when we see "basic building block" recipes like this fail, it's because they lack the corresponding types on the classpath to be able to accurately match the argument annotations. Does the project you're running this in have `com.mycom.mapping.ReportObject` available on the classpath when this recipe runs?

**Comment by chhex** [comment]
@timtebeek  great thanks for the quick reply... 

Yes the `@com.mycom.mapping.ReportObject ` is in the classpath , albeit via a Maven Profile...  that said: the project builds without problem. 

I also tried  the following: 

```
type: specs.openrewrite.org/v1beta/recipe
name: com.mycom.RemoveAnnotationExample
displayName: Remove annotation example
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@SuppressWarnings("all")'
```

on 

```

@SuppressWarnings("all")
public class AgpsArtMapper {
  ....
```

And nothing happend?

**Comment by timtebeek** [comment]
Do you see that working when you [fully qualify the argument annotationPattern](https://docs.openrewrite.org/reference/recipes/java/removeannotation)?
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.RemoveAnnotationExample
displayName: Remove annotation example
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@java.lang.SuppressWarnings("deprecation")'
```

**Comment by chhex** [comment]
Interesting, that works! But our „inhouse“ Annotations stemming from Xtend, don‘t

**Comment by chhex** [comment]
I did that , no avail ....

But interesting , i found that if i have : 
```
type: specs.openrewrite.org/v1beta/recipe
name: com.apgsga.RemoveAnnotationExample
displayName: Remove annotation example
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@com.affichage.mapping.ReportObject'
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@org.eclipse.xtext.xbase.lib.Pure'
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: '@java.lang.SuppressWarnings("all")'  
...
```
The annotations in the  testSourceDirectory are all removed! Cool , but only there .... i even added in the test sources in some sources the other two annotations... they are also removed. 

In the sourceDirectory non of the above annotations are removed, that also not  SuppressWarnings. So it is likely either a configuration issue of the Recipe itself or of Maven .... although for the later everything seems ok in terms of Maven.

I will look in more detail at the documentation , and possibly at the source Code
