### ISSUE TITLE
Maven - AddDependency - new options `skipIfTransitive`, `unless (gav)`

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#2932]
While testing the Spring Boot 3.0 recipe, we identified two undesirable behaviors with the Java upgrade recipe which handles javax -> jakarta:

* It adds `jakarta.servlet-api` as a direct dependency (when relevant) even if that dependency is already a transitive dependency on the project
* It adds `jakarta.servlet-api` (when relevant) even if `spring-boot-starter-web` is on the project (this starter includes a tomcat container dep which repackages an implementation of the same jakarta servlet-api code)

To fix these, we envision two new options on AddDependency (exact names TBD):

* `skipIfTransitive` - currently, AddDependency checks for an existing matching direct dependency in the project, and skips adding if found. This option would allow existing matching transitive deps to also trigger the skip behavior
* `unless` (list of GAVs) - do not add the dependency if one of these (arbitrary, seemingly-unrelated) deps is already on the classpath

With these options available, we could then adjust the relevant recipe in `rewrite-migrate-java` from this:

```yml
- org.openrewrite.maven.AddDependency:
    groupId: jakarta.servlet
    artifactId: jakarta.servlet-api
    version: 5.x
    onlyIfUsing: javax.servlet.* 
```

to this:

```yml
- org.openrewrite.maven.AddDependency:
    groupId: jakarta.servlet
    artifactId: jakarta.servlet-api
    version: 5.x
    onlyIfUsing: javax.servlet.*
    skipIfTransitive: true
    unless:
     - org.springframework.boot:spring-boot-starter-web 
```

I'm not fully convinced whether the `unless` option is likely to have other generic use cases in the future, though.

**Comment by jkschneider** [comment]
Agreed @nmck257.

**Comment by jkschneider** [comment]
@nmck257 can we make `unless` a general purpose applicable test instead?

**Comment by nmck257** [comment]
so, would that be a standalone visitor class, which can be invoked from yml with the recent declarative applicability test pattern?
is there another general-purpose applicable test I could use as a reference?

I think that makes sense

**Comment by shanman190** [comment]
So what I've been wondering if there should be a general purpose `not` applicability recipe. By having something like that we could then expand applicability tests to something such as:

```
applicability:
  singleSource:
    - org.openrewrite.NotApplicability:
        recipeList:
          - org.openrewrite.maven.search.DependencyInsight:
              groupId: org.springframework.boot
              artifactId: spring-boot-starter-web
recipeList:
- org.openrewrite.maven.AddDependency:
    groupId: jakarta.servlet
    artifactId: jakarta.servlet-api
    version: 5.x
    onlyIfUsing: javax.servlet.*
```

Which would cover this case and a number of other negative match cases that we've seen.
