### ISSUE TITLE
EqualsAvoidsNull removes too many parentheses

### ISSUE THREAD

**Issue by arthurvl** [openrewrite/rewrite#2950]
The java EqualsAvoidsNull recipe removes parentheses around rewritten comparisons. However, for some reason it is way more agressive in removing parentheses than it should be. The following test fails, when added to org.openrewrite.java.cleanup.EqualsAvoidsNullTest.java

```java
    @Test
    void keepNecessaryParens() {
        rewriteRun(
          java(
            """
            import java.util.Collection;

            public class EqualsAvoidsNullTestClass {
                public void triggersRecipe(String toCheck) {
                    if (toCheck != null && toCheck.equals("stringLiteral")) { }
                }

                public boolean triggersParenthesesRemoval() {
                    return (System.getProperties() != null) ? System.getProperties().keySet().isEmpty() : false;
                }

                public boolean needsToKeepParentheses() {
                    Collection<Object> set = System.getProperties().keySet();
                    return !(set == null || set.isEmpty());
                }
            }
            """,
            """
            import java.util.Collection;

            public class EqualsAvoidsNullTestClass {
                public void triggersRecipe(String toCheck) {
                    if ("stringLiteral".equals(toCheck)) { }
                }

                public boolean triggersParenthesesRemoval() {
                    return System.getProperties() != null ? System.getProperties().keySet().isEmpty() : false;
                }

                public boolean needsToKeepParentheses() {
                    Collection<Object> set = System.getProperties().keySet();
                    return !(set == null || set.isEmpty());
                }
            }
            """
          )
        );
    }
```

**Comment by timtebeek** [comment]
Thanks for the detailed report again!

**Comment by arthurvl** [comment]
My pleasure. I want to use OpenRewrite in my current modernization effort, but am hampered by having the results of applying the Java cleanup recipes on our codebase sometimes not even compilable.

Note that this test needs all three methods; removing either of the first two will not trigger the bug, as far a I've been able to determine.

**Comment by timtebeek** [comment]
Sorry to hear these imperfections are slowing you down, and thanks for reporting all of those in such detail!

Did you already know you can also easily create a subset of recipes to run through our builder, even for local runs?
You can for instance start at this composite recipe:
https://public.moderne.io/recipes/org.openrewrite.java.cleanup.CommonStaticAnalysis
From there (de)select any that you want to run, then press "Add selected to builder".
![image](https://user-images.githubusercontent.com/1027334/224162996-455b010e-464d-4a13-abae-173b9232f9a2.png)

That then brings you to our yaml recipe builder, where you can copy the yaml recipe to a local `rewrite.yml` fiile.
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.timtebeek.MyCustomRecipe
displayName: My custom recipe
description: Fix all the things.
recipeList:
  - org.openrewrite.java.cleanup.DefaultComesLast
  - org.openrewrite.java.cleanup.EmptyBlock
  - org.openrewrite.java.format.EmptyNewlineAtEndOfFile
  - org.openrewrite.java.cleanup.ForLoopControlVariablePostfixOperators
  - org.openrewrite.java.cleanup.FinalizePrivateFields
  - org.openrewrite.java.cleanup.MethodParamPad
```

This `rewrite.yml` can then be used directly in your local runs with the instructions here:
https://docs.openrewrite.org/running-recipes/running-rewrite-on-a-maven-project-without-modifying-the-build#running-a-recipe-with-configuration-parameters

Hope that at least helps you to run a large selection of recipes more easily, minus the recipes you want to exclude for now due to the issues reported. And always happy to help you on our Slack channel as well.
