### ISSUE TITLE
OrderImports with removeUnused=true removes types+annotations used in record components

### ISSUE THREAD

**Issue by fprochazka** [openrewrite/rewrite#2965]
I've created this config

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.fprochazka.Experiments
recipeList:
  - org.openrewrite.java.OrderImports:
      removeUnused: true
```

and then executed that over my project that uses a lot of records. It removed every import, that was used within a file _only_ in record components.
