### ISSUE TITLE
HideUtilityClassConstructor generates private constructor for java records

### ISSUE THREAD

**Issue by fprochazka** [openrewrite/rewrite#2966]
I've created this config

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.fprochazka.Experiments
recipeList:
  - org.openrewrite.java.cleanup.HideUtilityClassConstructor: { }
```

and then executed that over my project that uses a lot of records. It added private constructors to almost every single one, it skipped only those that had additional non-static methods.
