### ISSUE TITLE
java TabsAndIndents removes indents for record components (fields)

### ISSUE THREAD

**Issue by fprochazka** [openrewrite/rewrite#2968]
I've enabled `org.openrewrite.java.format.TabsAndIndents` 

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.fprochazka.Experiments
recipeList:
  - org.openrewrite.java.format.TabsAndIndents: { }

---
type: specs.openrewrite.org/v1beta/style
name: com.fprochazka.StyleExperiments
styleConfigs:
  - org.openrewrite.java.style.TabsAndIndentsStyle:
      useTabCharacter: false
      tabSize: 4
      indentSize: 4
      continuationIndent: 4
      indentsRelativeToExpressionStart: true # or false
      methodDeclarationParameters:
        alignWhenMultiple: false
```

and given this input 

```java
public class UserController
{

    // other methods

    public record RenameRequest(
        @NotBlank
        @JsonProperty("name") String name
    )
    {

    }
    
}
```

I would expect no changes, but it does this

```patch
     public record RenameRequest(
-        @NotBlank
-        @JsonProperty("name") String name
+    @NotBlank
+    @JsonProperty("name") String name
     )
```

the same happens when the record is the only type in a file 

----

I've tried to make sure the style config is loaded and it looks like it is 

![image](https://user-images.githubusercontent.com/158625/224502051-f05de15a-28b6-493f-90c1-1952c7e01a08.png)
