### ISSUE TITLE
ChangePackage skips some rewrites

### ISSUE THREAD

**Issue by m-ullrich** [openrewrite/rewrite#3091]
# Setup
- 2 classes in same folder (siblings)
- class bodies are empty
- 1 import of same package (`com.gargoylesoftware.htmlunit.html`) in each file
- the only difference is the imported class name (`HtmlPage` vs `HtmlElement`)

## Files
rewrite.Foo1.java:
```java
package rewrite;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
public class Foo1 {}
```

rewrite.Foo2.java:
```java
package rewrite;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
public class Foo2 {}
```

rewrite.yml:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: myReWrite
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: com.gargoylesoftware.htmlunit
      newPackageName: org.htmlunit

```
## Execution
Run Maven command with goal `rewrite:run` from inside eclipse

# Expected Behavior
Package of htmlunit imports changes from `com.gargoylesoftware.htmlunit` to `org.htmlunit` in both classes.
```java
// in Foo1
import org.htmlunit.html.HtmlPage;

// in Foo2
import org.htmlunit.html.HtmlElement;
```

# Observed Behavior
When running rewrite one class changes but not in the other. 

```java
// in Foo1
import org.htmlunit.html.HtmlPage;

// in Foo2
import com.gargoylesoftware.htmlunit.html.HtmlElement;
```

More precise the import of `HtmlPage` is modified on all executions of rewrite. No matter if it's in `Foo1` or `Foo2`.
Other imports of htmlunit (for example `HtmlElement` or `DomNode`) do never change. File does not matter either.
Also Windows vs Linux line endings don't matter, behavior is consistent.

![2023-04-05_23h49_53](https://user-images.githubusercontent.com/4802141/230224701-441413c9-4945-4eda-bcb0-63d99d1fe091.png)

Furthermore, as soon as `HtmlPage` is in the mix all imports of htmlunit package in that file get changed as expected. This does not work if other imports if htmlunit get combined.

Fail example (no HtmlPage):
```java
package rewrite;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
import com.gargoylesoftware.htmlunit.html.DomNode;
public class Foo1 {}
```

Success example (includes HtmlPage):
```java
package rewrite;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
public class Foo2 {}
```

![2023-04-06_00h29_57](https://user-images.githubusercontent.com/4802141/230226167-14cbd65d-132b-40a9-a11a-1cc825809ec0.png)

**Comment by knutwannheden** [comment]
@m-ullrich Thanks for reaching out. This seems very peculiar. The recipe should be able to handle multiple files, also if the import different types from a given package.

Are you with the same recipe both moving the types within the `com.gargoylesoftware.htmlunit.html` package or only changing references in types in other packages? Both cases are expected to work correctly.

It would be really helpful if you can create a small reproducible example and either attach it as a zip here or share it via GitHub. Thank you!

**Comment by m-ullrich** [comment]
Hi @knutwannheden , Thank you for the quick reply. I'm **only** changing the **references** in other packages. HtmlUnit is just a dependency in POM.

Please find an example project attached
[rewriteExample.zip](https://github.com/openrewrite/rewrite/files/11168742/rewriteExample.zip)

Just in case it's of any help, I'm using
- OpenRewrite `4.43.0`
- OpenJDK `"11.0.8" 2020-07-14`
- Apache Maven `3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)`
- Eclipse `2022-06 (4.24.0), build id: 20220609-1112`

**Comment by knutwannheden** [comment]
@m-ullrich I think what you are missing in your recipe is the `recursive: true` option (alternatively specify the "correct" package name). At least I think that should resolve your problem. Your recipe specifies `com.gargoylesoftware.htmlunit` as the old package name, even though all types are from the `com.gargoylesoftware.htmlunit.html` package.

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: myReWrite
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: com.gargoylesoftware.htmlunit
      newPackageName: org.htmlunit
      recursive: true
```

I will still keep this issue open, because I need to investigate, why some of the references were modified anyways. My intuition would have been that your recipe shouldn't have made any changes at all.
