### ISSUE TITLE
UpgradeDependencyVersion upgrading to Alpha version instead of the Final version

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite#3143]
Hi,

Still working on the Quarkus 3 upgrade recipes and I noticed an undesired behavior.

I have this artifact: https://repo1.maven.org/maven2/io/quarkiverse/githubapp/quarkus-github-app/maven-metadata.xml which has a few `2.0.0.Alphas` and a `2.0.0`. 

When applying the following rule:
```
 - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: io.quarkiverse.githubapp
      artifactId: '*'
      newVersion: 2.x
```

I end up with an upgrade to `2.0.0.Alpha2` and not `2.0.0`.

I'm not sure exactly how you resolve the version but currently https://central.sonatype.com/artifact/io.quarkiverse.githubapp/quarkus-github-app/2.0.0.Alpha2/versions doesn't have the `2.0.0` indexed as there apparently are some issues with some of the mirrors.

In any case, I had a few questions:

- Could you confirm that you use an ordering that will put `2.0.0` as newer than `2.0.0.Alpha2`?
- I suppose you're relying on Maven Central directly and not using REST APIs (from central.sonatype.com or search.maven.org) to get the versions, am I right? So I suppose it could be a mirror problem?

/cc @knutwannheden 

Thanks!

**Comment by gsmet** [comment]
FWIW, I have confirmed that using the following recipe upgrades to the final version so it can somehow find the new version (I also tested that if the version is not around, it won't update it). There might be something fishy with the way versions are ordered:

```
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: io.quarkiverse.githubapp
      artifactId: '*'
      newVersion: 2.0.0
```
