### ISSUE TITLE
RenamePropertyKey and ChangePropertyValue running together don't work as expected

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite#3144]
I have recipe that runs
```
- org.openrewrite.maven.RenamePropertyKey:
    oldKey: "version.foo"
    newKey: "version.bar"
- org.openrewrite.maven.ChangePropertyValue:
    key: "version.bar"
    newValue: "2.0"
    addIfMissing: false
    trustParent: true
```

When I give it
`<version.foo>1.0</version.foo>`
I get
`<version.bar>1.0</version.bar>`
instead of
`<version.bar>2.0</version.bar>`
Is there a way to "flush" between those 2 recipes?

[Slack Message](https://rewriteoss.slack.com/archives/C01A843MWG5/p1681994173982659?thread_ts=1681994173.982659&cid=C01A843MWG5)
