### ISSUE TITLE
Gradle Recipe AddDependency with variable version

### ISSUE THREAD

**Issue by nicolasb29** [openrewrite/rewrite#3209]
In the recipe "AddDependency", if we add a fixed version of a dependency, all is working fine :

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: AddJakartaXml
displayName: Add Jakarta XML
recipeList:
  - org.openrewrite.gradle.AddDependency:
      groupId: jakarta.xml.bind
      artifactId: jakarta.xml.bind-api
      version: "4.0.0"
      configuration: implementation
      onlyIfUsing: org.junit.jupiter.api.*
```

```yaml
implementation "jakarta.xml.bind:jakarta.xml.bind-api:4.0.0"
```

But if a variable version is added, the dependency is added multiple time:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: AddJakartaXml
displayName: Add Jakarta XML
recipeList:
  - org.openrewrite.gradle.AddDependency:
      groupId: jakarta.xml.bind
      artifactId: jakarta.xml.bind-api
      version: "${jakartaXmlVersion}"
      configuration: implementation
      onlyIfUsing: org.junit.jupiter.api.*
```

```yaml
 implementation "jakarta.xml.bind:jakarta.xml.bind-api:${jakartaXmlVersion}"
   implementation "jakarta.xml.bind:jakarta.xml.bind-api:${jakartaXmlVersion}"
   implementation "jakarta.xml.bind:jakarta.xml.bind-api:${jakartaXmlVersion}"
```
