### ISSUE TITLE
Gradle Recipe ChangeDependencyGroupId with variable version

### ISSUE THREAD

**Issue by nicolasb29** [openrewrite/rewrite#3239]
In the recipe "ChangeDependencyGroupId", if we add a fixed version of a dependency, all is working fine :

```yaml
implementation "javax.validation:validation-api:2.0.1.Final"
```

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: ModifyValidation
displayName: Modify Validation
recipeList:
  - org.openrewrite.gradle.ChangeDependencyGroupId:
      groupId: javax.validation
      artifactId: validation-api
      newGroupId: jakarta.validation
```

Result : 
```yaml
implementation "jakarta.validation:validation-api:2.0.1.Final"
```

But if a variable version is added, the dependency groupid is not modified:

```yaml
implementation "javax.validation:validation-api:${jakartaVersion}"
```

Result : 
```yaml
implementation "javax.validation:validation-api:${jakartaVersion}"
```
