### ISSUE TITLE
Gradle Recipe ChangeDependencyArtifactId with variable version

### ISSUE THREAD

**Issue by nicolasb29** [openrewrite/rewrite#3240]
In the recipe "ChangeDependencyArtifactId", if we add a fixed version of a dependency, all is working fine :

```yaml
implementation "javax.validation:validation-api:2.0.1.Final"
```

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: ModifyValidation
displayName: Modify Validation
recipeList:
  - org.openrewrite.gradle.ChangeDependencyArtifactId:
      groupId: javax.validation
      artifactId: validation-api
      newArtifactId: jakarta.validation-api
```

Result : 
```yaml
implementation "javax.validation:jakarta.validation-api:2.0.1.Final"
```

But if a variable version is added, the dependency artifactId is not modified:

```yaml
implementation "javax.validation:validation-api:${jakartaVersion}"
```

Result : 
```yaml
implementation "javax.validation:validation-api:${jakartaVersion}"
```
