### ISSUE TITLE
ChangePropertyKey not respecting sequentiality

### ISSUE THREAD

**Issue by JoseLora** [openrewrite/rewrite#3270]
Hi folks! I don't understand sequentiality in some OpenRewrite recipes. I reproduce this simple example:

```
public Sequential() {
    this.doNext(new ChangePropertyKey("common.tracing", "common.execution.context", true, null, null));
    this.doNext(new DeleteProperty("common.sleuth.send", null, null, null));
    this.doNext(new ChangePropertyKey("common.sleuth", "common.tracing", true, null, null));
  }
```
And this test should pass, but it fails because where I expect `common.tracing` appears as `common.execution.context`. If the changes are applied sequentially, it has no sense!

```
void changeOnlyDesiredProperties() {
    this.rewriteRun(yaml("""
        common:
          cache:
            enabled: true
          sleuth:
            send: true
            sender:
              http:
                username: user
                password: pwd
                connectionRequestTimeout: 5000
                timeout: 3000
                readTimeout: 3000
          blockhound.enabled: true
        """,
        """
            common:
              cache:
                enabled: true
              tracing:
                sender:
                  http:
                    username: user
                    password: pwd
                    connectionRequestTimeout: 5000
                    timeout: 3000
                    readTimeout: 3000
              blockhound.enabled: true
                    """));
  }
```

[Slack Message](https://rewriteoss.slack.com/archives/C01A843MWG5/p1684859716339379?thread_ts=1684859716.339379&cid=C01A843MWG5)
