### ISSUE TITLE
MergeYaml giving unexpected results where JSON path value of key includes wildcards

### ISSUE THREAD

**Issue by wabrit** [openrewrite/rewrite#3310]
I am using

- OpenRewrite v1.19.4
- Maven plugin org.openrewrite.maven:rewrite-maven-plugin:4.46.0

I'm attempting to use the MergeYaml recipe in this scenario:

_Old Yaml_
```yaml
list:
  services:
    foo:
      alpha: randomValue1
    bar:
      alpha: randomValue2
```

_New Yaml_
```yaml
list:
  services:
    foo:
      alpha: randomValue1
      beta: fixedValue
    bar:
      alpha: randomValue2
      beta: fixedValue
```

I tried using `MergeYaml` with key set to  `$.list.services.*` and yaml set to `beta: fixedValue`, but it gives me:

```yaml
list:
  services:
    foo:
      alpha: randomValue1
    bar:
      alpha: randomValue2
    beta: fixedValue
```
