### ISSUE TITLE
TabsAndIndents is not handling the indentation correctly on a lambda inside another lambda

### ISSUE THREAD

**Issue by BigBeaule** [openrewrite/rewrite#3362]
I am using
- OpenRewrite v8.1.3
- Maven plugin v5.2.4

I am using the Maven plugin on a single module project using the following YAML configuration:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: myRecipe
recipeList:
  - org.openrewrite.java.format.TabsAndIndents
---
type: specs.openrewrite.org/v1beta/style
name: myStyle
styleConfigs:
  - org.openrewrite.java.style.TabsAndIndentsStyle:
      useTabCharacter: false
      tabSize: 4
      indentSize: 4
      continuationIndent: 8
      indentsRelativeToExpressionStart: false
      methodDeclarationParameters:
        alignWhenMultiple: false
```

N.B. Don't look into the logic of the code since it's just to reproduce the issue.
When processing the following class that is formatted correctly with the Google formatting style in Eclipse:
```java
public class MyClass {
    public static void handleCollection(List<List<Object>> theList, Set<String> validIds, Set<String> validStates) {
        theList.forEach(element -> {
            // Filter internal elements to keep only valid and desired ones
            element.stream().filter(internalElement -> validIds.contains(internalElement.toString())
                    && validStates.contains(internalElement.toString())).forEach(internalElement -> {
                        internalElement.hashCode();
                        internalElement.equals(new Object());
                    });
        });
    }
}
```

It result in this undesired indentation change that gets flagged as a violation by Checkstyle:
```java
public class MyClass {
    public static void handleCollection(List<List<Object>> theList, Set<String> validIds, Set<String> validStates) {
        theList.forEach(element -> {
            // Filter internal elements to keep only valid and desired ones
            element.stream().filter(internalElement -> validIds.contains(internalElement.toString())
                    && validStates.contains(internalElement.toString())).forEach(internalElement -> {
                internalElement.hashCode();
                internalElement.equals(new Object());
            });
        });
    }
}
```

**My first thought was that [indentsRelativeToExpressionStart](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/style/TabsAndIndentsStyle.java#L34) would control this behavior. However, it seems like this parameter is never actually used in the code!**
