### ISSUE TITLE
Add fileMatcher to org.openrewrite.properties.AddProperty and org.openrewrite.properties.ChangePropertyValue

### ISSUE THREAD

**Issue by sarajend** [openrewrite/rewrite#3394]
## What problem are you trying to solve?
If you add or change a property as it is today, it is added to every `.properties` file in the project.

## Describe the solution you'd like
Would like to have a `fileMatcher` glob expression as input to the class. This can then be used in the `isAcceptable` methods in the `PropertiesVisitor` in order to determine if the current file should apply or not. 

## Have you considered any alternatives or workarounds?
No.

**Comment by timtebeek** [comment]
There's a bit of an interesting background to this; AddProperty and other similar recipes already had a fileMatcher pattern in the past; see for instance this commit: https://github.com/openrewrite/rewrite/commit/bf0ad252423c2679ffbd221d57a2081ca1758bea

These file matchers were subsequently removed when adding support for large repositories:
https://github.com/openrewrite/rewrite/commit/03c458404073082275a752063887c188d213afbe#diff-b209f02dd326367843cec9249b67cc621913a1ade6c111bb6050fd50db46a0e5L57

There's an ongoing discussion on how to best support limiting recipes to particular files. In rewrite v7.x we had applicability tests to limit execution, such that we did not have to add `fileMatcher`-type options to just any recipe, but could instead group together recipes that are only applied to files under certain conditions. We've had to revise that in v8.x to allow a streaming form of parsing and recipe execution, but are looking to reinstate this in some new (to be defined) form.

Hope that context helps; as soon as the above paragraph is captured in a GitHub Issue I'll try to link it here.

Meanwhile it might be best to create your own copy of AddProperty and ChangePropertyValue with a `fileMatcher` option, and use that until we have a better replacement. We're not actively looking to add those matcher options to existing recipes right now, as it would mean yet another breaking change if we choose to solve this differently as per the above.

**Comment by sdelamo** [comment]
+1 for adding a `fileMatcher` to `AddProperty`. I am trying to use it with a Micronaut Application, and it is a pity having to create an `AddProperty`copy.

**Comment by timtebeek** [comment]
Thanks for surfacing this issue again @sdelamo ! The solution we've added some time ago is to use Preconditions:
https://docs.openrewrite.org/reference/yaml-format-reference#preconditions
These can be used either with declarative (yaml) or imperative (Java & friends) recipes, to limit when a recipe should apply to a particular (singular) source.

Copying the example from the docs here for easy reference:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.PreconditionExample
preconditions:
  - org.openrewrite.text.Find:
      find: 1
recipeList:
  - org.openrewrite.text.ChangeText:
     toText: 2
```

Or if you'd want to use one of a number of different conditions:
https://docs.openrewrite.org/reference/yaml-format-reference#creating-or-preconditions-instead-of-and
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditions:
  - org.sample.FindAnyJson
recipeList:
  - org.openrewrite.json.ChangeKey:
      qwe: qwe
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindAnyJson
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/your.json"
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/our.json"
```

I hope that helps you there!

**Comment by sdelamo** [comment]
Thanks @timtebeek I was able to combine preconditions and recipes lists: 

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.liquibase
displayName: Adds Micronaut liquibase dependency in the compile classpath
recipeList:
  - io.micronaut.starter.feature.liquibase.dependencies
  - io.micronaut.starter.feature.liquibase.configuration
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.liquibase.configuration
displayName: Adds Micronaut liquibase configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: liquibase.datasources.default.change-log
      value: classpath:db/liquibase-changelog.xml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.liquibase.dependencies
displayName: Adds Micronaut liquibase dependency in the compile classpath
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: io.micronaut.liquibase
      artifactId: micronaut-liquibase
      configuration: implementation
      scope: compile
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/application.properties"
```
