### ISSUE TITLE
Ability to automatically close issues after a certain amount of time

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#340]
https://github.com/actions/stale

example: https://github.com/projectcontour/contour/blob/main/.github/workflows/stale.yaml

it would basically be this:

`.../stale.yml`

```yml
---
# https://github.com/marketplace/actions/close-stale-issues
name: stale
on:
  schedule:
    - cron: "0 0 * * *" # end of every day, "at 00:00"
  workflow_dispatch: {} # can be ran manually if desired, I suppose

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: "This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          days-before-issue-stale: 90
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
```
