### ISSUE TITLE
ChangePropertyValue automatically coalesces properties

### ISSUE THREAD

**Issue by wabrit** [openrewrite/rewrite#3426]
Given a source YAML that looks like this:

```yaml
quarkus:
  opentelemetry:
    enabled: true
```
and a recipe `ChangePropertyKey("quarkus.opentelemetry.enabled", "quarkus.otel.enabled", ..)`

the result is

```yaml
quarkus:
  otel.enabled: true
```

This automatic coalescing of property names confuses Quarkus, which treats the new property as `quarkus."otel.enabled"` and doesn't match it to `quarkus.otel.enabled`.

The correct output in this case would be:

```yaml
quarkus:
  otel:
    enabled: true
```
