### ISSUE TITLE
filePattern has no effect with FindAndReplace and Find recipes 

### ISSUE THREAD

**Issue by mduerig** [openrewrite/rewrite#3532]
# What version of OpenRewrite are you using?
I am using org.openrewrite.recipe:rewrite-recipe-bom:2.2.1

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a multi module project.
Local `rewrite.yml` from [this example](https://docs.openrewrite.org/recipes/text/findandreplace).

```
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.FindAndReplaceExample
displayName: Find and replace example
recipeList:
  - org.openrewrite.text.FindAndReplace:
      find: blacklist
      replace: denylist
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.java'
```

`$ mvn rewrite:run -Drewrite.activeRecipes=com.yourorg.FindAndReplaceExample`

## What did you expect to see?
Occurrences of `blacklist` replaced with `denylist` in **Java files only**.

## What did you see instead?
Occurrences of `blacklist` replaced with `denylist` in non Java files too. For example in `rewrite.yml` itself.
