### ISSUE TITLE
FindAndReplace AlreadyReplaced idempotency wrong

### ISSUE THREAD

**Issue by StWitte** [openrewrite/rewrite#3548]
Using:
- rewrite-recipe-bom:2.3.0
- rewrite-core:8.5.0
- rewrite-maven-plugin: 5.5.0

My project is a single module Spring-boot 2.x application.

The FindAndReplace recipe doesn't execute the second FindAndReplace recipe in the same file as the first one. 
(In `if(sourceFile.getMarkers().findFirst(AlreadyReplaced.class).isPresent())` it detects that the file is already replaced but this was the first replace recipe. )

If the order of the 2 FindAndReplace recipes is changed again only the first one is executed. 

Here's a test case reproducing the problem:

```java
	@Test
	void findAndReplaceMultiple() {
		rewriteRun(
				spec -> spec.recipes(
						new FindAndReplace(".to(\"http4:", "\\.to(\"http:", null, null, null, null, "**/*.java"),
						new FindAndReplace("${property.", "\\$\\{exchangeProperty\\.", null, null, null, null, "**/*.java")
				),
				text("""
					   .to("Mail uri property: ${property.mail_uri}")
					   .to("http4:myapp/token?throwExceptionOnFailure=false")
					""", """
					   .to("Mail uri property: ${exchangeProperty.mail_uri}")
					   .to("http:myapp/token?throwExceptionOnFailure=false")
					""",
				        spec -> spec.path("test1.java")
				),
				text("""
					   .to("Mail uri property: ${exchangeProperty.mail_uri}")
					   .to("http:myapp/token?throwExceptionOnFailure=false")
					""",
					// No changes
				        spec -> spec.path("test2.java")
				)
			);
	}
```
Same thing happens when applied from a yaml file:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: my.1To2Migration.FindAndReplace
displayName: 1 to 2 migration replacements
recipeList:
  - org.openrewrite.text.FindAndReplace:
      find: "${property."
      replace: "\\$\\{exchangeProperty\\."
      regex: false
      filePattern: '**/*.java'
  - org.openrewrite.text.FindAndReplace:
      find: ".to(\"http4:"
      replace: ".to(\"http:"
      regex: false
      filePattern: '**/*.java'
``` 
 
As replied in [Slack ](https://rewriteoss.slack.com/archives/C01A843MWG5/p1694604623704379):
"seems like a bug on how to detect idempotency on the recipe via a single Marker."
