### ISSUE TITLE
Idempotent print issue in YAML for Block scalar styles with anchors

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#3632]
```yaml
data: &anc |
    @this is a long string@
bar: *anc
```
