### ISSUE TITLE
Rewrite fails to parse java file with /*****/ comment line

### ISSUE THREAD

**Issue by n-semikin** [openrewrite/rewrite#3639]
## Issue description
Code sample:
```java
package org.example.parsing_error;

public class SomeClass {

    /**********************************************************/

    interface InterfaceA {
    }
}
```

This file is failed to be processed by the Rewrite. If we remove InterfaceA then file is parsed fine. Otherwise there is the error:

```log
20231020_13:13:56.505 [INFO] Using active recipe(s) [com.test.Test_UpdateMovedPackageClassName]
20231020_13:13:56.505 [INFO] Using active styles(s) []
20231020_13:13:59.636 [INFO] Validating active recipes...
20231020_13:13:59.799 [INFO] Project [TestRewrite] Resolving Poms...
20231020_13:14:00.188 [INFO] Project [TestRewrite] Parsing source files
20231020_13:14:01.296 [WARNING] There were problems parsing some source files, run with --errors to see full stack traces
20231020_13:14:01.297 [WARNING] There were problems parsing src/main/java/org/example/parsing_error/SomeClass.java
```

The reason for the issue is that rewrite attempts to parse the comment line as a Javadoc and fails.
So if after the line like this /****/ there is a java statement it fails to parse the java-file.

## What version of OpenRewrite are you using?
I am using
- Maven plugin v5.8.1
- rewrite-migrate-java v2.1.1
- maven version 3.6.3, running via maven-wrapper

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.
```xml
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.8.1</version>
                <configuration>
                    <activeRecipes>
                        <recipe>com.test.Test</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>2.1.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

Run plugin command:
```shell
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run
```

rewrite.yml:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.test.Test
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: com.sun.javafx.scene.control.skin.TableHeaderRow
      newFullyQualifiedTypeName: javafx.scene.control.skin.TableHeaderRow
      ignoreDefinition: false
```

## What is the smallest, simplest way to reproduce the problem?
```java
package org.example.parsing_error;

public class SomeClass {

    /****************/

    interface InterfaceA {
    }

}
```
