### ISSUE TITLE
Add new optional parameter newMethodName to ChangeMethodTargetToStatic recipe

### ISSUE THREAD

**Issue by alexandrenavarro** [openrewrite/rewrite#3647]
## What problem are you trying to solve?
I want to replace some static method from a class to another class with potentially another method name.
Ex : migrate Guava to commons-lang (or the contrary), this kind of method exists in spring or log4j notably
com.google.common.base.Strings.Strings.isNullOrEmpty -> org.apache.commons.lang3.StringUtils.isEmpty

## Describe the solution you'd like
Add new optional parameter newMethodName defaulted to methodName by default to the ChangeMethodTargetToStatic recipe.

## Have you considered any alternatives or workarounds?
No.

Thanks in advance.

**Comment by timtebeek** [comment]
Hi @alexandrenavarro ; You can already achieve such a migration by combining two recipes together, as for instance seen here:
https://github.com/openrewrite/rewrite-static-analysis/blob/6d9048c86852119be4d552907b404e788fc2efc6/src/main/resources/META-INF/rewrite/java-best-practices.yml#L44-L53

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.staticanalysis.ReplaceValidateNotNullHavingSingleArgWithObjectsRequireNonNull
displayName: Replace `org.apache.commons.lang3.Validate#notNull` with `Objects#requireNonNull`
description: 'Replace `org.apache.commons.lang3.Validate.notNull(Object)` with `Objects.requireNonNull(Object)`.'
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.apache.commons.lang3.Validate notNull(Object)
      newMethodName: requireNonNull
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.commons.lang3.Validate requireNonNull(Object)
      fullyQualifiedTargetTypeName: java.util.Objects
```

This way each recipe focuses on just one aspect, while together they accomplish a complete migration. Not how the second recipe matches on the non-existing `Validate requireNonNull`, yet still is able to change the type.

We prefer this approach of combining recipes, rather than adding additional options to each recipe for combinations of operations to apply. We have added a recipe builder to aid in composing such existing recipes together: https://app.moderne.io/recipes/builder

I hope that helps! And if you compose and want to share any such recipes to got from Guava to Commons-Lang, those would fit right in here: https://github.com/openrewrite/rewrite-migrate-java/tree/main/src/main/java/org/openrewrite/java/migrate/guava
