### ISSUE TITLE
Pick TabsAndIndentsStyle from .editorconfig

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite#3666]
## What problem are you trying to solve?

I am trying to duplicate the configuration between `.editorcofig` and OpenRewrite.

## Describe the solution you'd like

I would like OpenRewrite to infer `TabsAndIndentsStyle` settings from https://editorconfig.org/ settings

## Have you considered any alternatives or workarounds?

Frankly speaking, I have not.

## Additional context

https://editorconfig.org/ is a well-known standard for configuring common IDE settings, and many IDEs support `.editorconfig` files natively.
It would be great if OpenRewrite could reuse the settings from there.

`.editorconfig` settings are flexible: the settings can be divided into several files, and the indent style can vary across files.

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

I am about to integrate OpenRerwite, so I am not sure I would have time to implement editorconfig support.

**Comment by timtebeek** [comment]
And since you mentioned you're integrating OpenRewrite, I thought you might also be interested to try out https://app.moderne.io . That's a platform we've built to help OSS projects run OpenRewrite recipes, and I've gone ahead and made [pgjdbc available there](https://app.moderne.io/organizations/pgjdbc/pgjdbc?branch=master&origin=github.com) as well. That means you can now run recipes such as this one to move from explicit types to diamond operators against pgjdbc: https://app.moderne.io/results/pH1ciJE1x
![image](https://github.com/openrewrite/rewrite/assets/1027334/87feba90-11cd-47cd-8e34-7e56d46438fb)

With the top right corner button you can start a PR to get this resolved, and then run some of the other 1300 recipes as well. Hope that helps!

**Comment by vlsi** [comment]
> When no explicit style is provided, we autodetect the style and match that when we change code

In practice, Gradle plugin resorts to `checkstyle.xml` in case the project has `checkstyle` configured, and there's no way to opt out of that.
That means `autoconfiguration` is not triggered in my case.

In my experience, Checkstyle produces non-actionable warnings, so I am leaning towards moving the configuration to `.editorconfig` in case it is possible.

For pgjdbc, I have to add

```yaml
  - org.openrewrite.java.style.SpacesStyle:
      # See https://github.com/openrewrite/rewrite/blob/1d0aeec11e2d7f239f2f656bfd964b17ca8e4d17/rewrite-java/src/main/java/org/openrewrite/java/style/SpacesStyle.java#L26C14-L26C25
      other:
        afterForSemicolon: true
```

otherwise OpenRewrite removes spaces after semicolons in `for` loops.
