### ISSUE TITLE
Bug: OpenRewrite maven plugin makes changes even if there is no checkstyle violations

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [openrewrite/rewrite#3761]
## What version of OpenRewrite are you using?
I am using

- OpenRewrite v8.10.1
- Maven/Gradle plugin v5.14.1
- rewrite-static-analysis v1.1.1

## How are you running OpenRewrite?

I am working on https://github.com/strimzi/strimzi-kafka-operator/issues/9394. The project has a checkstyle configuration available [here](https://github.com/strimzi/strimzi-kafka-operator/blob/main/.checkstyle/checkstyle.xml).
I am using the Maven plugin, and the project is a multi-module project.
```xml
<plugin>
    <groupId>org.openrewrite.maven</groupId>
    <artifactId>rewrite-maven-plugin</artifactId>
    <version>5.14.1</version>
    <configuration>
        <activeRecipes>
            <recipe>org.openrewrite.staticanalysis.CodeCleanup</recipe>
        </activeRecipes>
        <exclusions>
            <exclusion>.git/**</exclusion>
            <exclusion>*.yaml</exclusion>
            <exclusion>*.yml</exclusion>
        </exclusions>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-static-analysis</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?
```java
class A {
    void foo(String bar) {
        int i = 5;
    }
}
```
One of the issues faced is about creating a constructor. If there is no constructor defined, then, it automatically adds it although there is no checkstyle violations. 
Another case is about spaces before braces. If there is some gap between `)` and `{`, the plugin completely removes the gap although there is no checkstyle violations.

## What did you expect to see?

```java
class A {
    void foo(String bar) {
        int i = 5;
    }
}
```

## What did you see instead?

```java
class A {
   private A {
   }
    void foo(String bar){
        int i = 5;
    }
}
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I don't exactly know what the cause of this problem is. If any maintainers or community members can explain me the cause of the problem, I would love to work on it :grin:.

**Comment by timtebeek** [comment]
That ought to help to use the same configuration; beyond that it's very possible that an initial run of `CodeCleanup` will produce more changes than what's configured in in CheckStyle alone. The Code Cleanup recipe is composed of some 21 other recipes:
https://docs.openrewrite.org/recipes/staticanalysis/codecleanup

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.staticanalysis.CodeCleanup
displayName: Code cleanup
description: Automatically cleanup code, e.g. remove unnecessary parentheses, simplify expressions.
recipeList:
  - org.openrewrite.staticanalysis.DefaultComesLast
  - org.openrewrite.staticanalysis.EmptyBlock
  - org.openrewrite.java.format.EmptyNewlineAtEndOfFile
  - org.openrewrite.staticanalysis.ForLoopControlVariablePostfixOperators
  - org.openrewrite.staticanalysis.FinalizePrivateFields
  - org.openrewrite.java.format.MethodParamPad
  - org.openrewrite.java.format.NoWhitespaceAfter
  - org.openrewrite.java.format.NoWhitespaceBefore
  - org.openrewrite.java.format.PadEmptyForLoopComponents
  - org.openrewrite.staticanalysis.TypecastParenPad
  - org.openrewrite.staticanalysis.EqualsAvoidsNull
  - org.openrewrite.staticanalysis.ExplicitInitialization
  - org.openrewrite.staticanalysis.FallThrough
  - org.openrewrite.staticanalysis.HideUtilityClassConstructor
  - org.openrewrite.staticanalysis.NeedBraces
  - org.openrewrite.staticanalysis.OperatorWrap
  - org.openrewrite.staticanalysis.UnnecessaryParentheses
  - org.openrewrite.staticanalysis.ReplaceThreadRunWithThreadStart
  - org.openrewrite.staticanalysis.ChainStringBuilderAppendCalls
  - org.openrewrite.staticanalysis.ReplaceStringBuilderWithString
  - org.openrewrite.java.ShortenFullyQualifiedTypeReferences
```
If you only want to apply changes from a subset of those recipes, you can create your own `rewrite.yml` using only those recipes. Name the recipe differently, and configure your rewrite-maven-plugin to use your own recipe as the only active recipe.
