### ISSUE TITLE
YAML Parser support for Helm Charts

### ISSUE THREAD

**Issue by ghost** [openrewrite/rewrite#3782]
## What problem are you trying to solve?

For those organizations that are using Helm, it is common for helm charts to include templating directives. 

As an example: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-configmap
data:
  JAVA_OPTS: "{{.Values.javaOpts }}"
```

https://helm.sh/docs/chart_template_guide/values_files/

## Describe the solution you'd like

It would be nice to have a specialized version of the YAML parser that is aware of the template syntax.

## Have you considered any alternatives or workarounds?

Currently, any Helm chart that has template directives will generate a parsing exception from the YAML parser.

The above example results in the follow warning during parsing: 

`There were problems parsing helm/service-configmap.yaml`

## Additional context

This would likely have to be a specialized parser that is aware of the template directives.
