### ISSUE TITLE
MergeYaml recipe fileMatcher property is present in 7.x version but removed in 8.x versions

### ISSUE THREAD

**Issue by vijay-chavakula** [openrewrite/rewrite#3856]
MergeYaml recipe **_fileMatcher_** is present in 7.x version but removed in 8.x version
causing the recipe changes to apply to all yml files in project and not only to specific files.

I am using

- OpenRewrite recipe bom V2.3.1
- Maven compiler plugin v3.8.0
- rewrite-yaml v8.7.2 and 8.11.1

## How are you running OpenRewrite?

Are you using the Maven plugin, Gradle plugin, Moderne CLI, Moderne.io or something else?
Maven plugin 
Is your project a single module or a multi-module project?
Single Module
Can you share your configuration so that we can rule out any configuration issues?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>3.8.0</version>
</plugin>
<dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-yaml</artifactId>
      <scope>compile</scope>
</dependency>
```
```yaml
org.openrewrite.yaml.MergeYaml:
      key: $
      yaml: >
        tasks:
          preBuild:
            - closure: startServer
         
      acceptTheirs: false
      fileMatcher: '**/jules.yml'
      objectIdentifyingProperty: name
```

## What is the smallest, simplest way to reproduce the problem?
using the declarative approach of the above mentioned recipe in creating our own recipe and compile and run the jar on our projects to will apply the yaml changes to all the yml files in the project structure not only to jules.yml. 

## What did you expect to see?
We are expecting to revert the changes done to **_MergeYaml_** recipe to include back **_fileMatcher_** property and apply changes only to those files.
Like in above example only to jules.yml in all directories of project.

## What did you see instead?
Right now after 8.x versions as the fileMatcher property is removed we see the changes getting applied to all the yml files in the project which is not expected. 

## What is expected to be done to fix it?
Earlier the code for the 7.11.0 and above version is 
```java
 @Override
    protected TreeVisitor<?, ExecutionContext> getSingleSourceApplicableTest() {
        return new HasSourcePath<>(fileMatcher);
    }
```
We need similar code to check which files to have the changes applied.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
No

**Comment by timtebeek** [comment]
Hi @vijay-chavakula ! We have indeed removed file matchers from individual recipes are recommend that folks use Preconditions instead:
- https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices#use-preconditions
- https://docs.openrewrite.org/reference/yaml-format-reference#preconditions

Preconditions allow you to limit where recipes are applied, similar to how you used `fileMatcher` before. For that you can use FindSourceFiles as a precondition:
- https://docs.openrewrite.org/recipes/core/findsourcefiles

By using preconditions we no longer have to add `fileMatcher` options to some of the 1300+ recipes that we maintain, which helps simplify our individual recipe implementations. I hope that context and link to the docs helps!

I'll close this issue as I don't think there's anything to do on our side at the moment, but you can still reply and ask follow up questions below. If it turns out there's something to be done still we can reopen the issue.

**Comment by vijay-chavakula** [comment]
hi @timtebeek, I tried in declarative approach for Preconditions. 
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: net.example.recipe.yaml.AddingCassandraEnv
displayName: sample jules file
description: "sample jules file"
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/jules.yml"
recipeList:
  - org.openrewrite.yaml.MergeYaml:
      key: $
      yaml: >
        buildConfig:
          env: 
            variables: 
              - CASSANDRA_HOST: "127.0.0.1"
      acceptTheirs: false
      objectIdentifyingProperty: value
```
## What does above precodition do? 
It checks if jules.yml is found in project and then if found then it appends the yaml content to all the yml files and not to jules.yml file.
