### ISSUE TITLE
Disable value property resolution in org.openrewrite.maven.AddProperty

### ISSUE THREAD

**Issue by jpraet** [openrewrite/rewrite#3892]
## What problem are you trying to solve?

With this recipe

```
  - org.openrewrite.maven.AddProperty:
      key: java_home
      value: ${java_home.jdk21}
      trustParent: true
```

I'm trying to add `<java_home>${java_home.jdk21}</java_home>`  to the properties in the pom.xml.
Where the <java_home.jdk21> property is defined in the ~/.m2/settings.xml on the developer workstations.
(in my case C:\tools\redhat-jdk21, but this can be different for other devs, and on our build server).

Unfortunately the property is set with the resolved value to `<java_home>C:\tools\redhat-jdk21</java_home>`.

## Describe the solution you'd like

An option to escape / disable the maven property resolution.
