### ISSUE TITLE
CreateTextFile recipe operates in root dir instead of module

### ISSUE THREAD

**Issue by abetaev-equinix** [openrewrite/rewrite#3893]
## What version of OpenRewrite are you using?

I am using

- Gradle plugin (how do I check the version? it uses latest, but I don't have any direct dependencies on Openrewrite)

## How are you running OpenRewrite?

I am using the Gradle plugin, and my project is a multi-module project.
I have
```
root
|- module
|  |- ...
|  '- submodule
|- ...
|- gradlew
|- rewrite.yaml
|- init.gradle
'- build.gradle.kts
```

## What is the smallest, simplest way to reproduce the problem?

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.CreateGradleProperties
recipeList:
  - org.openrewrite.text.CreateTextFile:
      relativeFileName: gradle.properties
      fileContents: |
        group={{groupId}}
        rdomain={{rdomain}}
```

```sh
./gradlew module:submodule:rewriteRun --init gradle.init
``` 

## What did you expect to see?

`gradle.properties` is created in `module/submodule/` directory.

## What did you see instead?

`gradle.properties` is created in root directory.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

If this is a bug, I can think of how this can be fixed.
[The plugin's documentation](https://docs.openrewrite.org/recipes/text/createtextfile) does not state what is path relative to. I would expect the module where task runs, as per the [Gradle plugin documentation](https://docs.openrewrite.org/reference/gradle-plugin-configuration):
> When applied to a multi-project build, plugin behavior differs depending on whether the plugin is applied to the root project or to a sub-project. Applied to the root project, the plugin will parse and refactor all sources from all projects. Applied to any project other than the root project, the plugin will parse and refactor only sources from that project.
