### ISSUE TITLE
org.openrewrite.properties.ChangePropertyValue not available?

### ISSUE THREAD

**Issue by Evodam** [openrewrite/rewrite#3897]
I tried to change a property's value according to https://docs.openrewrite.org/recipes/properties/changepropertyvalue

I created a rewrite.yml that contained this:

```
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ChangeOracleJdbc
displayName: Swap old groupId of com.oracle.jdbc with newer com.oracle.database.jdbc
recipeList:
  - org.openrewrite.properties.ChangePropertyValue:
      propertyKey: oracle.connector.version
      newValue: 21.6.0.0.1
  - org.openrewrite.maven.ChangeManagedDependencyGroupIdAndArtifactId:
      oldGroupId: com.oracle.jdbc
      oldArtifactId: ojdbc8
      newGroupId: com.oracle.database.jdbc
      newArtifactId: ojdbc11
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: com.oracle.jdbc
      oldArtifactId: ojdbc8
      newGroupId: com.oracle.database.jdbc
      newArtifactId: ojdbc11
```

I ran it using mvn org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=com.yourorg.ChangeOracleJdbc

In console this recipe is not executed:
![grafik](https://github.com/openrewrite/rewrite/assets/119758828/0f5cd5f6-ae52-4a8c-934f-ecf5c8ede02c)

When changing the recipe to "org.openrewrite.maven.ChangePropertyValue" it works:
![grafik](https://github.com/openrewrite/rewrite/assets/119758828/86799ef3-813e-4712-9a19-934724ce5106)

Am I using it wrong?
