### ISSUE TITLE
Declarative Preconditions - `or` association

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#4003]
## What problem are you trying to solve?
Declarative preconditions currently associate via `AND` if you declare multiple on the same recipe.
If you want to achieve an `OR` relationship, you can do it, but through a much more verbose "diamond" pattern.

Sample:
```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
recipeList:
  - org.sample.DoSomething.condition.1
  - org.sample.DoSomething.condition.2
  - org.sample.DoSomething.condition.3

---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething.condition.1
displayName: Do Something (condition 1)
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
recipeList:
  - org.sample.DoSomething.for.real

---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething.condition.2
displayName: Do Something (condition 2)
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/your.json"
recipeList:
  - org.sample.DoSomething.for.real  

---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething.condition.3
displayName: Do Something (condition 3)
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/our.json"
recipeList:
  - org.sample.DoSomething.for.real

---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething.for.real
displayName: Do Something (for real)
recipeList:
  - org.openrewrite.json.ChangeKey:
      qwe: qwe

```
(if you imagine graphing how those 5 recipes relate to each other, it kinda looks like a diamond)

## Describe the solution you'd like

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditionAssociation: OR
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/your.json"
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/our.json"
recipeList:
  - org.openrewrite.json.ChangeKey:
      qwe: qwe

```

## Have you considered any alternatives or workarounds?
Support for passing nested recipes as recipe arguments in declarative recipes? :)
This could allow something like:

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditionAssociation: OR
preconditions:
  - org.openrewrite.Preconditions.Or:
      recipeList:
        - org.openrewrite.FindSourceFiles:
            filePattern: "**/my.json"
        - org.openrewrite.FindSourceFiles:
            filePattern: "**/your.json"
        - org.openrewrite.FindSourceFiles:
            filePattern: "**/our.json"
recipeList:
  - org.openrewrite.json.ChangeKey:
      qwe: qwe

```

## Additional context

cc @sambsnyd 

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

Assuming we can bless a design, yeah, I suspect the code won't be too treacherous

**Comment by timtebeek** [comment]
Up to now we've mostly tried to keep logic out of the declarative recipes; one approach I haven't seen listed above is this alternative, non-diamond:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditions:
  - org.sample.FindAnyJson
recipeList:
  - org.openrewrite.json.ChangeKey:
      qwe: qwe
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindAnyJson
recipeList:
  - org.sample.FindMyJson
  - org.sample.FindYourJson
  - org.sample.FindOurJson
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindMyJson
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindYourJson
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/your.json"
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindOurJson
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/our.json"
```
(I have not run this example, but I think it should work)

This approach would be something akin to a rake; still somewhat verbose, but at least no duplication in the actual work that ought to be done. Could this be a suitable (and then also documented) alternative to having an explicit OR associativity?

**Comment by nmck257** [comment]
Oh, I think the rake could be even simpler:

```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditions:
  - org.sample.FindAnyJson
recipeList:
  - org.openrewrite.json.ChangeKey:
      qwe: qwe
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindAnyJson
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/your.json"
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/our.json"
```
At that point, yeah, documenting that pattern feels like a pretty strong alternative to the original ideas in this issue.

**Comment by timtebeek** [comment]
That's even better indeed; saves a couple of exposed recipes too.

@mike-solomon would you be able to document Nick's pattern for folks that want _any_ precondition to match, as opposed to _all_?

That would then close this issue without any code changes.

**Comment by mike-solomon** [comment]
> That's even better indeed; saves a couple of exposed recipes too.
> 
> @mike-solomon would you be able to document Nick's pattern for folks that want _any_ precondition to match, as opposed to _all_?
> 
> That would then close this issue without any code changes.

Yep - I expanded the precondition documentation here: https://github.com/openrewrite/rewrite-docs/commit/8499db832653ee100552eb02476bc3d24da58042 -- please let me know if that makes sense or if I should rephrase/add additional information.

**Comment by timtebeek** [comment]
Yes looks good, thanks!

**Comment by samuliwritescode** [comment]
Hi all! Unfortunately the documented example above does not work. Used here the rewrite-maven-plugin version 5.39.2 to test this and it looks like if the precondition is in another recipe, then the precondition is not hit at all. For example this simplified case with only one precondition does not change anything in my.json:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditions:
  - org.sample.FindAnyJson
recipeList:
  - org.openrewrite.json.ChangeKey:
      oldKeyPath: $.qwe
      newKey: ewq
---
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.FindAnyJson
recipeList:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
```

while this does:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.DoSomething
displayName: Do Something
preconditions:
  - org.openrewrite.FindSourceFiles:
      filePattern: "**/my.json"
recipeList:
  - org.openrewrite.json.ChangeKey:
      oldKeyPath: $.qwe
      newKey: ewq
```
