### ISSUE TITLE
Declarative Preconditions - Control applicability to ScanningRecipes

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#4005]
## What problem are you trying to solve?
Suppose you want to add a dependency to a Maven project, but only if some other condition is true in the `pom.xml`.
You might try something like this:

```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.Example
displayName: Use AddDependency with a declarative precondition
preconditions:
  - org.openrewrite.maven.FindDependency:
      groupId: org.glassfish.jaxb
      artifactId: *
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: org.glassfish.jaxb
      artifactId: jaxb-runtime
      version: latest.release
      onlyIfUsing: jakarta.xml.bind..*
```
...but this will never pass Preconditions, because `AddDependency`'s scanner targets Java files, but the declarative precondition only matches on Maven files. And declarative preconditions always apply to both the scan and edit phases.

## Describe the solution you'd like
Could be solved with a new, optional enum field:
```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.sample.Example
displayName: Use AddDependency with a declarative precondition
preconditionPhases: edit # or "scan", or (default) "all"
preconditions:
  - org.openrewrite.maven.FindDependency:
      groupId: org.glassfish.jaxb
      artifactId: *
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: org.glassfish.jaxb
      artifactId: jaxb-runtime
      version: latest.release
      onlyIfUsing: jakarta.xml.bind..*
```

## Have you considered any alternatives or workarounds?
- Imperative recipes
- Individual toggle arguments (eg `preconditionsOnScanning: false`, `preconditionsOnEdit: false`)
- Separate precondition sequences per desired phase (eg `scanningPreconditions: # one or more recipes`, `editPreconditions: # one or more recipes`), while the existing `preconditions` option continues to mean "both scan and edit phase"

## Additional context

cc @sambsnyd 

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

Assuming we can bless a design, yeah, I suspect the code won't be too treacherous
