### ISSUE TITLE
Add or merge content to yaml file

### ISSUE THREAD

**Issue by nicolasb29** [openrewrite/rewrite#4010]
## What problem are you trying to solve?
I have a yaml file and I want to append (or merge) yaml content to it

## What precondition(s) should be checked before applying this recipe?
If the input content is yaml

## Describe the situation before applying the recipe
```yaml
existing-content:
  languages:
    - french
    - english
```

## Describe the situation after applying the recipe

With input content 

```yaml
new-content:
  country:
    - France
    - UK
```

I want to have

```yaml
existing-content:
  languages:
    - french
    - english
new-content:
  country:
    - France
    - UK
```

## Have you considered any alternatives or workarounds?
I tried with AppendToTextFile but I have an exception `java.lang.ClassCastException: class org.openrewrite.yaml.tree.Yaml$Documents cannot be cast to class org.openrewrite.text.PlainText `

It is working with `org.openrewrite.java.spring.AddSpringProperty`
