### ISSUE TITLE
org.openrewrite.gradle.RemoveDependency does not remove dependency in subproject

### ISSUE THREAD

**Issue by travisboettcher** [openrewrite/rewrite#4033]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite BOM 2.6.4
- Gradle plugin 6.8.2

I've also tested with OpenRewrite 2.7.1 and Gradle plugin 6.8.4.

## How are you running OpenRewrite?
I am running OpenRewrite using Gradle, as a multi-module project. The attached zip contains a simplified version of the project structure.

## What is the smallest, simplest way to reproduce the problem?
The attached zip reproduces the issue - when using the org.openrewrite.gradle.RemoveDependency to remove a dependency, the specified dependency does not get removed.

## What did you expect to see?
The subproject build.gradle should be updated, to remove the dependency

## What did you see instead?
The subproject build.gradle does not get updated

Interestingly, if I add the dependency to the top-level build.gradle and run the recipe, both do get removed.

Gradle project with issue reproduced:
[OpenRewriteIssueReproduced.zip](https://github.com/openrewrite/rewrite/files/14375426/OpenRewriteIssueReproduced.zip)

**Comment by timtebeek** [comment]
Hi @travisboettcher ; thanks for the report! Haven't found time to run your sample yet, but figured show the contents in the issue. 
![image](https://github.com/openrewrite/rewrite/assets/1027334/9a66df98-1bf2-4727-a03c-e30c0cd61137)

Ideally we replicate this with a unit test, and we have some mechanisms for that as well through our various SourceSpecs and Assertions classes. We'll need to see if the problem replicates there, as indeed it's unfortunate to not have this work for you.

## ./build.gradle
```groovy
plugins {
    id 'java'
    id "org.openrewrite.rewrite" version "6.8.2"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

rewrite {
    activeRecipe("com.example.RemoveHibernateEntityManager")
}

dependencies {
    rewrite(platform("org.openrewrite.recipe:rewrite-recipe-bom:2.6.4"))
}
```

## ./settings.gradle
```groovy
rootProject.name = 'OpenRewrite-example'
include 'example'
```

## ./example/build.gradle
```groovy
plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.hibernate:hibernate-entitymanager:5.6.15.Final'
}

test {
    useJUnitPlatform()
}
```

## ./rewrite.yml
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.RemoveHibernateEntityManager
displayName: Remove org.hibernate:hibernate-entitymanager
recipeList:
  - org.openrewrite.gradle.RemoveDependency:
      groupId: org.hibernate
      artifactId: hibernate-entitymanager
```
