### ISSUE TITLE
rewrite.yml does not affect changes in java code

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite#41]
I am trying to reproduce this example: https://docs.openrewrite.org/java/refactoring-java-source-code/usestaticimport

I created single class in project:
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class Sample {
  @Test
  void sample() {
    Assertions.assertEquals(42, 21*2);
  }
}
```

Then I created in the root of the project **rewrite.yml**:

```yml
---
type: specs.org.openrewrite.org/v1beta/visitor
name: io.moderne.UseStaticJUnitAsserts
visitors:
  - org.openrewrite.java.UseStaticImport:
    method: 'org.junit.jupiter.api.Assertions assert*(..)'
```

My pom also contains plugin:
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>1.2.1</version>
                <configuration>
                    <configLocation>rewrite.yml</configLocation>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

But I don't get expected result when I run the command: `./mvnw rewrite:fix`

```java
// What I expected to see
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Sample {
  @Test
  void sample() {
    assertEquals(42, 21*2);
  }
}
```

More over I noticed that when I remove **rewrite.yml** it doesn't affect anything. Build status is always "SUCCESS".

Also when I change **rewrite.yml** in https://github.com/openrewrite/spring-petclinic-migration it always applies the same changes(even when I remove **rewrite.yml**).

Did I miss something? Seems like I don't understand something...
