### ISSUE TITLE
Maven: Allow version exclusions for all Upgrade*Version recipes

### ISSUE THREAD

**Issue by smurf667** [openrewrite/rewrite#4127]
## What problem are you trying to solve?

In my company we operate an internal Maven repository which sometimes contains "weird" versions of artifacts (this is probably not limited to the internal registry...). For example, completely ignoring the Maven version formats, sometimes a version has a hashcode, like "9abcdef". This might be considered a very high version number during upgrading, higher than "normal" ones like "1.0.1" or "3.2.1".

As far as I can tell, all the `Upgrade*Version` recipes pull the version information from Maven metadata and then try to use the "newest". Above situation - which I cannot influence - inadvertently leads to a bogus update, not the latest version, but some "junky" one.

The Maven versions plugin supports a "rule set": https://www.mojohaus.org/versions/versions-model/rule.html
This way, it is possible to ignore certain versions.

## Describe the solution you'd like

Ideally, all  `Upgrade*Version` recipes offered a way to specify which versions should **not** be considered as acceptable update values.
Maybe they all could accept a similar input to the above described Maven versions ruleset?
For example, a property `ignorableVersions` of type `String[]` containing regular expressions to match ignorable versions could be introduced.

Example use:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.UpgradePluginVersionExample
displayName: Upgrade Maven plugin version example
recipeList:
  - org.openrewrite.maven.UpgradePluginVersion:
      groupId: org.openrewrite.maven
      artifactId: rewrite-maven-plugin
      ignorableVersions:
        - "9abcdef"
        - ".*[aA][lL][pP][hH][aA].*"
```

This could be applied before considering the list of available versions (see for example https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java#L160 of `UpgradePluginVersion`).

## Have you considered any alternatives or workarounds?

I considered checking the update result after running the recipe and discarding "bad" updates, however this would mean that for anything where the update is bad, this dependency would **never** be updated, which is not what I am looking for.

## Additional context

I've looked at the backlog, but did not find anything similar. Apologies if this is a duplicate.

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

I am unsure about the code base, and if and how you would implement the feature I describe. I could assist with code or reviews, but I have only limited time available.
