### ISSUE TITLE
ChangeType erroneously changes package of unrelated type

### ISSUE THREAD

**Issue by kennytv** [openrewrite/rewrite#4182]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.26.0-SNAPSHOT (via `org.openrewrite.recipe:rewrite-recipe-bom:latest.integration`)
- Gradle plugin v6.13.0

## How are you running OpenRewrite?

Very simple setup with just two classes and a single recipe via the Gradle plugin. Ignoring Java target and snapshot repository declaration, the build file looks like this:
```kts
plugins {
    base
    `java-library`
    id("org.openrewrite.rewrite") version "6.13.0"
}

dependencies {
    implementation(platform("org.openrewrite.recipe:rewrite-recipe-bom:latest.integration"))
}

rewrite {
    activeRecipe(
        "test.ChangeTypeTest",
    )
}
```

## What is the smallest, simplest way to reproduce the problem?
Create two classes in the same package, where the class that should *not* be changed makes some kind of reference to a class that *should* be changed (e.g. via method parameters/return values, or generic type parameters):
```java
package com.test; // This will erroneously be changed

public final class Test {

    public A test() { // Any reference to A is required for the issue
        return new A();
    }
}
```
```java
package com.test;

public final class A { // This will correctly be moved to the subpackage
}
```

The recipe used:
```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: test.ChangeTypeTest
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: com.test.A
      newFullyQualifiedTypeName: com.test.sub.A
```

## What did you expect to see?
`A` to be moved without further changes to `Test`

## What did you see instead?
The package declaration of `Test` changes to `com.test.sub`. It also fails to add an import for `A`, but that might just be a result of the relevant issue here

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Sure. I am vaguely familiar with visitor patterns through ASM, although I'd imagine an active contributor might be able to fix this faster than telling me what to look for
