### ISSUE TITLE
java/ChangePackage does not update JPMS module-info.java

### ISSUE THREAD

**Issue by commonquail** [openrewrite/rewrite#4257]
## What version of OpenRewrite are you using?

7b498e603b8a951618d5e8e674a66fd87bcfeb03

## How are you running OpenRewrite?

Maven plugin with

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ChangePackageExample
displayName: Rename package name example
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: com.yourorg.foo
      newPackageName: com.yourorg.bar
```

on any project with a `module-info.java` that `exports com.yourorg.foo`.

## What is the smallest, simplest way to reproduce the problem?

```java
module example {
  exports com.yourorg.foo;
}
```

## What did you expect to see?

```java
module example {
  exports com.yourorg.bar;
}
```

## What did you see instead?

`module-info.java`s are ignored.
