### ISSUE TITLE
Change Dependency recipes do not work with dependencies defined in jvm-test-suites

### ISSUE THREAD

**Issue by sihutch** [openrewrite/rewrite#4373]
I am using

- OpenRewrite v6.17.1
- Maven/Gradle plugin v6.17.1
- Gradle v7.6.4

## How are you running OpenRewrite?
I am running OpenRewrite using the Gradle Plugin, and my project is a single module project.

My build.gradle has the same dependency defined in the main dependencies and also with a jvm-test-suites section as shown below

```groovy
dependencies {
    rewrite("org.openrewrite.recipe:rewrite-java-dependencies:1.14.0")
    implementation"javax.servlet:javax.servlet-api:3.1.0"
}

testing {
    suites {
        test {
            useJUnitJupiter()
            dependencies {
                implementation project()
                implementation"javax.servlet:javax.servlet-api:3.1.0"
            }
        }
    }
}
```
When I run either of the two recipes shown below only the `javax.servlet:javax.servlet-api:3.1.0` in the main dependencies section is changed. 

1. org.openrewrite.java.dependencies.ChangeDependency
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.sihutch.ChangeDependencyExample
displayName: Change Gradle or Maven dependency example
recipeList:
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: javax.servlet
      oldArtifactId: javax.servlet-api
      newGroupId: jakarta.servlet
      newArtifactId: jakarta.servlet-api
      newVersion: 6.x
```

1. org.openrewrite.gradle.ChangeDependency

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.sihutch.ChangeGradleDependencyExample
displayName: Change Gradle dependency example
recipeList:
    - org.openrewrite.gradle.ChangeDependency:
          oldGroupId: javax.servlet
          oldArtifactId: javax.servlet-api
          newGroupId: jakarta.servlet
          newArtifactId: jakarta.servlet-api
          newVersion: 6.x
```

I have created an example project [here](https://github.com/sihutch/open-rewrite-test-suite-example)

I was expecting the dependencies in the jvm-test-suite block to also be changed. Can you please confirm whether this is a bug or something that is not implemented ? If that later, is there another recipe that you can recommend that can handle the jvm-test-suite case ?

Thanks

Si
