### ISSUE TITLE
Support for changing versions in TOML files

### ISSUE THREAD

**Issue by michaelmcfadyensky** [openrewrite/rewrite#4400]
## What problem are you trying to solve?
We specify all of our dependencies and their versions inside toml files for our gradle projects. We would like a away to automate the upgrading of these versions via open rewrite.

## Describe the solution you'd like
Recipe available for changing the version of a dependency specified in a toml file

## Have you considered any alternatives or workarounds?
Consider using the find and replace recipe but it leads to several work arounds having to be in place for it to work.

## Additional context
https://rewriteoss.slack.com/archives/C01A843MWG5/p1723123348552829

**Comment by timtebeek** [comment]
@steplica thanks a lot for the offer to help!
1. I think in the early stages of getting the parser to work @KnutWannheden might be best to guide you, as he's been most active with recent parser developments. I'd expect `rewrite-toml` should still be part of `openrewrite/rewrite`, with an eye towards integration with Gradle
2. once the parser works we'd need to hook it into the [rewrite-maven-plugin](https://github.com/openrewrite/rewrite-maven-plugin) and [rewrite-gradle-plugin](https://github.com/openrewrite/rewrite-gradle-plugin), and [rewrite-polyglot](https://github.com/openrewrite/rewrite-polyglot)
3. then once files are parsed as Toml, we'd need to integrate with our Gradle support; at that point we can tag Shannon Pamperl (also here) for guidance, likely looking towards our Trait support to minimize recipe changes

**Comment by tompson** [comment]
will this also support gradle version catalogs defined in `settings.gradle` (no toml files involved) ?

**Comment by jizhangattw** [comment]
👍 sounds good. keep an eye on this issue.

**Comment by timtebeek** [comment]
- One step closer after https://github.com/openrewrite/rewrite/pull/4845

**Comment by shanman190** [comment]
Next steps:
- [ ] Update `gradle.UpgradeDependencyVersion` to handle dependencies from the Gradle Version Catalog `libraries` table with the version appearing in a String literal [1]
- [ ] Update `gradle.UpgradeDependencyVersion` to handle dependencies from the Gradle Version Catalog `libraries` table with the version appearing within the defined inline table [2]
- [ ] Update `gradle.UpgradeDependencyVersion` to handle dependencies from the Gradle Version Catalog `libraries` table with a version reference being used [3]
- [ ] Update `gradle.plugins.UpgradePluginVersion` to handle plugins from the Gradle Version Catalog `plugins` table with the version appearing in a String literal [4]
- [ ] Update `gradle.plugins.UpgradePluginVersion` to handle plugins from the Gradle Version Catalog `plugins` table with the version appearing within the defined inline table [5]
- [ ] Update `gradle.plugins.UpgradePluginVersion` to handle plugins from the Gradle Version Catalog `plugins` table with a version reference being used [6]


[1]
```gradle
dependencies {
    implementation(libs.guava)
}
```

```toml
[libraries]
guava = "com.google.guava:guava:29.0-jre"
```


[2]
```gradle
dependencies {
    implementation(libs.guava)
}
```

```toml
[libraries]
guava = { group = "com.google.guava", name = "guava", version = "29.0-jre" }
```


[3]
```gradle
dependencies {
    implementation(libs.guava)
}
```

```toml
[versions]
guava = "29.0-jre"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
```


[4]
```gradle
plugins {
    alias(libs.plugins.openrewrite)
}
```

```toml
[plugins]
openrewrite = "org.openrewrite.rewrite:5.40.0"
```


[5]
```gradle
plugins {
    alias(libs.plugins.openrewrite)
}
```

```toml
[plugins]
openrewrite = { id = "org.openrewrite.rewrite", version = "5.40.0" }
```

[6]
```gradle
plugins {
    alias(libs.plugins.openrewrite)
}
```

```toml
[versions]
openrewrite = "5.40.0"

[plugins]
openrewrite = { id = "org.openrewrite.rewrite", version.ref = "openrewrite" }
```


Links:
- https://docs.gradle.org/current/userguide/version_catalogs.html
