### ISSUE TITLE
RemoveUnused YAML visitor

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#448]
Remove unused YAML mapping and sequence entries (and empty mappings and sequences), recursively.

For example, `a` and `b` would be removed in this YAML:

```yaml
root:
  a:
    b:
  c: 0
```
