### ISSUE TITLE
addProperty creates a new gradle.properties file instead of adding new properties when running in multi-module project. 

### ISSUE THREAD

**Issue by desantisernesto** [openrewrite/rewrite#4497]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.33.8
- Gradle plugin v8.4

## How are you running OpenRewrite?
I'm running openrewrite over a multi-module project, it seems to be key in this bug. 

## What is the smallest, simplest way to reproduce the problem?

My project has the following structure
gradle.properties
settings.gradle
api-grpc/build.gradle
server/build.gradle

There are not a build.gradle file at the root. 

The gradle.properties file has several properties, like:
```
my.property.number1=1
my.property.number2=2
```

My recipe adds several properties:
```
recipeList:
 - org.openrewrite.gradle.AddProperty:
     key: my.property.jakarta
     value: 1
     overwrite: false
     filePattern: 'gradle.properties'
 - org.openrewrite.gradle.AddProperty:
     key: my.property.boot3
     value: 1
     overwrite: true
     filePattern: 'gradle.properties'

```

## What did you expect to see?
```
my.property.number1=1
my.property.number2=2
my.property.jakarta=1
my.property.boot3=1
```

## What did you see instead?
It is resulting in a new properties file without any of the original properties and just the first property of my recipe:
```
my.property.jakarta=1
```

## What is the full stack trace of any errors you encountered?
In the log is possible to see it is re creating the file:
```
Generated new file gradle.properties by:
    org.openrewrite.gradle.AddProperty: {key=my.property.jakarta, value=1, overwrite=true, filePattern=gradle.properties}
```

NOTE: When I added a build.gradle file at the root of the project, it works fine!

## Are you interested in [contributing a fix to OpenRewrite]
I'm, but I don't have enough experience to do it now. If someone can help me, I can try to fix this issue.
