### ISSUE TITLE
Dependencies are removed when upgrading version number.

### ISSUE THREAD

**Issue by jesuistombe** [openrewrite/rewrite#4537]
Hi there,

I tried a simple recipe to upgrade the version of a package I use:
```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.company.Upgrade
displayName: Migrate to new version
recipeList:
  - org.openrewrite.maven.UpgradeParentVersion:
      groupId: com.company.package
      artifactId: "*"
      newVersion: 7.0.0
```
To invoke the recipe, I used `mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=com.company.Upgrade`.

I expected this recipe to change that version and do nothing else, however it removed a bunch of dependencies from my pom.xml. These might have been unused or unnecessary, but it is still an undesired behaviour. Is there a way to disable this?
