### ISSUE TITLE
Recipe does not exist

### ISSUE THREAD

**Issue by jesuistombe** [openrewrite/rewrite#4538]
I tried to execute the following [recipe](https://docs.openrewrite.org/recipes/java/spring/renamebean):
```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.RenameBeanExample
displayName: Rename bean example
recipeList:
  - org.openrewrite.java.spring.RenameBean:
      type: foo.MyType
      oldName: fooBean
      newName: barBean
```
I executed it using `mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=com.yourorg.RenameBeanExample` but got the following error:

```
[ERROR] Recipe validation error in org.openrewrite.java.spring.RenameBean: Recipe class org.openrewrite.java.spring.RenameBean cannot be found
```

What am I doing wrong here?
