### ISSUE TITLE
ChangePropertyValue could improve array value behaviour

### ISSUE THREAD

**Issue by Jenson3210** [openrewrite/rewrite#4593]
## What problem are you trying to solve?
In our yamls we want to update an entry of a list in the yaml with a certain text value by another text value. If we would fo this with a simple text Find/Replace, the other occurences outside the propertyKey binding would also be updated. 

## Describe the situation before applying the recipe
```yaml
job-name4:
  script:
    - replaceme
    - replaceme
    - do not replaceme
    - replaceme should not be done
  rules:
    - replaceme
```

## Describe the situation after applying the recipe
When running with regex false for replaceme -> replaced
```yaml
job-name4:
  script:
    - replaced
    - replaced
    - do not replaceme
    - replaceme should not be done
  rules:
    - replaceme
```

When running with regex true for (.\*)replaceme(.\*) -> $1replaced$2
```yaml
job-name4:
  script:
    - replaced
    - replaced
    - do not replaced
    - replaced should not be done
  rules:
    - replaceme
```

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
The branch is present
