### ISSUE TITLE
MergeYaml snippet recipe not working

### ISSUE THREAD

**Issue by ashutoshk2206** [openrewrite/rewrite#4736]
I am trying to use MergeYaml recipe of open-rewrite following the example shared here - https://docs.openrewrite.org/recipes/yaml/mergeyaml
But this is not working and I keep getting error mentioned below

## What version of OpenRewrite are you using?

I am using
- Maven plugin v5.46.1

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
			<plugin>
				<groupId>org.openrewrite.maven</groupId>
				<artifactId>rewrite-maven-plugin</artifactId>
				<version>5.46.1</version>
				<configuration>
					<exportDatatables>true</exportDatatables>
					<activeRecipes>
						<recipe>com.yourorg.CreateYamlFileExample</recipe>
					</activeRecipes>
				</configuration>
			</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

Below is the content of my `rewrite.yml`
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.MergeYamlExample
displayName: Merge YAML snippet example
recipeList:
  - org.openrewrite.yaml.MergeYaml:
      key: $.spec
      yaml:
        lastName: kumar
      acceptTheirs: false
      filePattern: test.yml
```

And this is my `test.yml` (where the recipe would run and make changes adding lastName: kumar at the end of the file)

```yaml
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
spec:
  bucketPolicyOnly: true

```

## What did you expect to see?

```yaml
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
spec:
  bucketPolicyOnly: true
  lastName: kumar
```

## What did you see instead?
I see below error

```
[INFO] Using active recipe(s) [com.yourorg.MergeYamlExample]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[ERROR] Recipe validation error in org.openrewrite.yaml.MergeYaml: Unable to load Recipe: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openrewrite.yaml.MergeYaml["yaml"])
[ERROR] Recipe validation errors detected as part of one or more activeRecipe(s). Execution will continue regardless.
```

**Comment by ashutoshk2206** [comment]
Got it working by using yaml folded style. Can someone please confirm if the documentation needs to be corrected. I will be more than happy to open a PR.

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.MergeYamlExample
displayName: Merge YAML snippet example
recipeList:
  - org.openrewrite.yaml.MergeYaml:
      key: $.spec
      yaml: >
        lastName: kumar
      acceptTheirs: false
      filePattern: test.yml
```
