### ISSUE TITLE
Dependencies of plugins are not updated

### ISSUE THREAD

**Issue by jonblack** [openrewrite/rewrite#4779]
Using the following example recipe:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.my.group.Example
displayName: Example
description: Example
recipeList:
  - org.openrewrite.maven.ChangePluginGroupIdAndArtifactId:
      oldGroupId: com.my.group
      oldArtifactId: app-plugin-artifact
      newGroupId: com.my.group.subgroup
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: com.my.group
      oldArtifactId: app-plugin-artifact
      newGroupId: com.my.group.subgroup
  - org.openrewrite.maven.ChangeManagedDependencyGroupIdAndArtifactId:
      oldGroupId: com.my.group
      oldArtifactId: app-plugin-artifact
      newArtifactId: app-plugin-artifact
      newGroupId: com.my.group.subgroup
```

This fails to update the dependencies of plugins. For example:

```xml
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.app.myapp</groupId>
  <artifactId>awesome-app</artifactId>
  <version>1.0.0</version>

  <build>
    <plugins>
      <plugin>
        <groupId>com.app.plugins</groupId>
        <artifactId>cool-plugin</artifactId>
        <version>1.0.0</version>
        <dependencies>
          <dependency>
            <groupId>com.my.group</groupId>
            <artifactId>app-plugin-artifact</artifactId>
            <version>1.1.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
</project>
```

I would expect at least one of these recipes to update the groupId of the plugin dependency. If there is a recipe that can do this, it's not clear to me which one it would be.
