### ISSUE TITLE
Does not group Yaml properties correctly

### ISSUE THREAD

**Issue by diegosilval** [openrewrite/rewrite#4802]
## What version of OpenRewrite are you using?

I am using

- rewrite-maven-plugin v5.47.0
- Maven v 3.9.9
- rewrite-spring v5.25.0

## How are you running OpenRewrite?

I am using the Maven plugin from command line.
```shell
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run  \
  -Drewrite.activeRecipes=com.sample.MyYamlRecipe \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:LATEST

```

And `rewrite.yml`
```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.sample.MyYamlRecipe
recipeList:
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: "app.rhino"
      newPropertyKey: "rhino"
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: "app.security.header"
      newPropertyKey: "rhino.security.header"
```

## What is the smallest, simplest way to reproduce the problem?

```yml
app:
  security:
    header:
      enabled: false
  rhino:
    config:
      props:
        - prop: 'name1'
          config[0]:
            prop1: 1
            prop2: 2
        -
          prop: 'name2'
          config[0]:
            prop1: 3
            prop2: 4
```

## What did you expect to see?

```yml
rhino:
  security:
    header:
      enabled: false
  config:
    props:
      - prop: 'name1'
        config[0]:
          prop1: 1
          prop2: 2
      -
        prop: 'name2'
        config[0]:
          prop1: 3
          prop2: 4
```

## What did you see instead?

```yml
rhino:
  config:
    props:
      - prop: 'name1'
        config[0]:
          prop1: 1
          prop2: 2
      -
                            prop: 'name2'
                            config[0]:
                              prop1: 3
                              prop2: 4
rhino.security.header:
  enabled: false

```
