### ISSUE TITLE
UpdateGradleWrapper fails for a custom wrapperUri with placeholders

### ISSUE THREAD

**Issue by bmuschko** [openrewrite/rewrite#4816]
## What version of OpenRewrite are you using?

- OpenRewrite v8.41.0

## How are you running OpenRewrite?

Moderne.io

Is your project a single module or a multi-module project? Single

Can you share your configuration so that we can rule out any configuration issues?

```
type: specs.openrewrite.org/v1beta/recipe
...
recipeList:
  - org.openrewrite.gradle.UpdateGradleWrapper:
       version: 8.9
       distribution: bin
       wrapperUri: https://services.gradle.org/distributions/gradle-${version}-${distribution}.zip
```

## What is the smallest, simplest way to reproduce the problem?

Run the [org.openrewrite.gradle.UpdateGradleWrapper](https://docs.openrewrite.org/recipes/gradle/updategradlewrapper) recipe with the [declarative YAML format](https://docs.openrewrite.org/reference/yaml-format-reference).

## What did you see instead?

An error with a stack trace when executing the recipe.

## What is the full stack trace of any errors you encountered?

```
java.lang.IllegalArgumentException: Illegal character in path at index 50: https://services.gradle.org/distributions/gradle-${version}-${distribution}.zip
  java.base/java.net.URI.create(URI.java:906)
  org.openrewrite.gradle.UpdateGradleWrapper.getGradleWrapper(UpdateGradleWrapper.java:139)
  ...
```

## Are you interested in [contributing a fix to OpenRewrite]

Yes
