### ISSUE TITLE
Changing a tag into a variable-containing-one replaces it with the value at run time

### ISSUE THREAD

**Issue by svaningelgem** [openrewrite/rewrite#4840]
## What version of OpenRewrite are you using?
I am using

- OpenRewrite master branch

## How are you running OpenRewrite?
```mvn rewrite:run```

## What is the smallest, simplest way to reproduce the problem?
```yaml
  - org.openrewrite.xml.AddOrUpdateChildTag:
      parentXPath: //dependency[groupId="com.example.ws4"]
      newChildTag: "<groupId>${some.variable}</groupId>"
```

## What did you expect to see?
That the `groupId` would be replaced by `${some.variable}`.

## What did you see instead?
That the `groupId` was replaced by `com.example.ws4`.

```text
[WARNING] Changes have been made to war\pom.xml by:
[WARNING]                 org.openrewrite.xml.AddOrUpdateChildTag: {parentXPath=//dependency[groupId="com.example.ws4"], newChildTag=<groupId>com.example.ws4</groupId>}
```

**Comment by svaningelgem** [comment]
FYI, this works though:
```yaml
  - org.openrewrite.xml.ChangeTagValue:
      elementName: //dependency/groupId
      oldValue: "^com\\.example\\.ws.$"
      newValue: "\\$\\{some.variable}"
      regex: true
```
