### ISSUE TITLE
Potential Issue with Handling Parent-Child Relationships in Multi-Module Maven Projects

### ISSUE THREAD

**Issue by torsten-liermann** [openrewrite/rewrite#4948]
A potential issue with an OpenRewrite recipe in a multi-module Maven project has been identified. The recipe is intended to add a dependency when a specific plugin is present. In the module without a parent relationship, this works as expected, whereas in the module with a parent relationship, no change occurs. A demo project illustrating this behavior is available at: https://github.com/torsten-liermann/openrewrite-maven-multi-module-issue-demo

```
type: specs.openrewrite.org/v1beta/recipe
name: demo-009
preconditions:
  - org.openrewrite.maven.search.FindPlugin:
      groupId: org.codehaus.mojo
      artifactId: jaxb2-maven-plugin
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: jakarta.xml.bind
      artifactId: jakarta.xml.bind-api
      version: 4.0.*
```

`mvnw org.openrewrite.maven:rewrite-maven-plugin:LATEST:run -Drewrite.activeRecipes=demo-009`

At first glance, it seems that OpenRewrite encounters issues when the parents of Maven modules are included in the reactor build. This setup is common in more complex projects. It is not uncommon for aggregator pom.xml files to be referenced as parents in submodules.

Perhaps it is worth mentioning that this is likely not an issue with FindPlugin or the preconditions themselves. There must be problems in handling parent-child relationships, as I mentioned in previous reports
