### ISSUE TITLE
ChangePackage doesn't handle classes with GWT JNSI methods

### ISSUE THREAD

**Issue by auke-** [openrewrite/rewrite#4995]
## What version of OpenRewrite are you using?

I am using OpenRewrite v8.44.2 with the [ChangePackage](https://docs.openrewrite.org/recipes/java/changepackage) recipe.

## What is the smallest, simplest way to reproduce the problem?

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ChangePackageExample
displayName: Rename package name example
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: old_package_name
      newPackageName: new_package_name
```

```java
package old_package_name;
class A {
  native void alert(String msg) /*-{ $wnd.alert(msg); }-*/;
}
```

## What did you expect to see?

```java
package new_package_name;
class A {
  native void alert(String msg) /*-{ $wnd.alert(msg); }-*/;
}
```

## What did you see instead?
OpenRewrite didn't touch the file. It seems like it ignores Java classes with `native` methods and/or trailing comment.

See [reproducer](https://github.com/openrewrite/rewrite/pull/4996)
