### ISSUE TITLE
`MergeYaml` edge case: keeps comment at the end of the doc after appending an entry

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#5135]
See the test below:

```java
    @Test
    void insertInSequenceEntriesWithDeepSearchWithComment_1() {
        rewriteRun(
          spec -> spec.recipe(new MergeYaml(
            "$..containers",
            "imagePullPolicy: Always",
            true,
            null,
            null,
            null,
            null
          )),
          yaml(
            """
              kind: Pod
              spec:
                containers:
                  - name: <container name>  # comment
              """,
            """
              kind: Pod
              spec:
                containers:
                  - name: <container name>  # comment
                    imagePullPolicy: Always
              """
          )
        );
    }
```

This fails because `# comment` is in DocumentEnd node rather than the yaml block. Not sure what to propose... I'd probably try to keep the inline comment as part of the entry... Or perhaps have a special case for the comment at the end of the document if this would be a less intrusive fix.

**Comment by greg-at-moderne** [comment]
Thanks for reporting this. It's even more interesting.
With the following input:
```yaml
kind: Pod
spec:
  containers:
    - name: <container name>  # comment
t1: t1 # t1
t2: t2 # t2
```
the logic gets even more confused with the comments:
```yaml
kind: Pod
spec:
  containers:
    - name: <container name> # t1
      imagePullPolicy: Always  # comment
t1: t1 # t1
t2: t2 # t2
```

There's definitely built-in support for handling the trailing comments, but I think it's imperfect and is not handling the case like this.
