### ISSUE TITLE
Replace two array properties in .yml files

### ISSUE THREAD

**Issue by fbeaufume** [openrewrite/rewrite#5241]
## What problem are you trying to solve?

In all .yml files, I need to replace two "array" properties ("families" by "groups" and "members" by "users" in the next example).

Can this be achieved using org.openrewrite.yaml.ChangePropertyKey or other standard recipes ?

## Sample input and expected output

Sample input:

```
application.families:
  - name: Name1
    members:
      - name: John
        age: 20
      - name: Jane
        age: 30
  - name: Name2
    members:
      - name: Thomas
        age: 40
```

Expected output:

```
application.groups:
  - name: Name1
    users:
      - name: John
        age: 20
      - name: Jane
        age: 30
  - name: Name2
    users:
      - name: Thomas
        age: 40
```

## What I tried

I tried using:

```
  # This changes nothing
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: "application.families.members"
      newPropertyKey: "application.families.users"
  # This correctly replaces "families" by "groups"   
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: "application.families"
      newPropertyKey: "application.groups"
  # This changes nothing
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: "application.groups.members"
      newPropertyKey: "application.groups.users"
```
