### ISSUE TITLE
org.openrewrite.java.cleanup.Cleanup breaks class @SpringBootApplication

### ISSUE THREAD

**Issue by rbosse** [openrewrite/rewrite#538]
Hi,

The cleanup recipe includes org.openrewrite.java.cleanup.HideUtilityClassConstructor and this one adds a private constructor to the class annotated with @SpringBootApplication.  This will prevent the Spring Boot Application to run.

Thanks

**Comment by aegershman** [comment]
Hi @rbosse -- good catch, thanks for logging this. That's being looked into. 

In the mean time, I don't want you to be stuck, so if you're interested, you can add this to your `rewrite.yml` config file in the project root to tell `HideUtilityClassConstructorStyle` to ignore any classes which are annotated with `@SpringBootApplication`:

```yml
type: specs.openrewrite.org/v1beta/style
name: com.example.cleanup.HideUtilityClassConstructorSuppression
styleConfigs:
  - org.openrewrite.java.cleanup.HideUtilityClassConstructorStyle:
      ignoreIfAnnotatedBy:
        - "@lombok.experimental.UtilityClass"
        - "@lombok.Data" # if you're using lombok, etc.
        - "@org.springframework.boot.autoconfigure.SpringBootApplication"
```

and then activate it along with your other config in your `pom.xml` with this, for example:

```xml
...
<activeRecipes>
    <recipe>org.openrewrite.java.cleanup.Cleanup</recipe>
</activeRecipes>
...
<activeStyles>
    <style>com.example.cleanup.HideUtilityClassConstructorSuppression</style>
</activeStyles>
```

(or similarly in your `gradle` build file, full examples are in the [maven-plugin](https://docs.openrewrite.org/reference/rewrite-maven-plugin) and [gradle-plugin](https://docs.openrewrite.org/reference/gradle-plugin-configuration) reference docs)

If you try that out and run into any issues, let me know and I'll help out as soon as possible. No worries if not, just trying to make sure you aren't blocked 👍
