### ISSUE TITLE
Kotlin Recipe Declarative String Arguments Instantiate as Empty String

### ISSUE THREAD

**Issue by ryan-hudson** [openrewrite/rewrite#5545]
As of OpenRewrite 8.50.0, String options passed declaratively into Kotlin recipes are being instantiated as "". 

Debugging a bit, it looks like this issue was caused by [this](https://github.com/openrewrite/rewrite/commit/ffca900d5866aecff0c00e09c76413b7301bbf4d#diff-4f7f19d4eafba083e6cda1dc9b9b8689b8c664e3afe65374e59897f7ac2f152e) change to the Recipe Loader, which is now delegating recipe instantiation to `RecipeIntrospectionUtils.constructRecipe`, which sets Kotlin String arguments to "" [here](https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java#L123-L127). That logic appears to have been added purely for validation, and was not intended to instantiate recipe args. 
- See https://github.com/openrewrite/rewrite/issues/3508

## What version of OpenRewrite are you using?
8.54.0

## How are you running OpenRewrite?
Unit Tests in private repo. 

### Declarative Yaml
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: net.sample.kotlin.KotlinReplaceAllRecipeWrapper
displayName: Kotlin Replace All Wrapper
description: Tests a simple Kotlin recipe that replaces all text with the provided option.
recipeList:
  - net.sample.kotlin.KotlinReplaceAllRecipe:
      replacementText: "REPLACEMENT_TEXT"
```

### Imperative Kotlin Recipe
```kotlin
package net.sample.kotlin

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import org.openrewrite.*
import org.openrewrite.text.PlainText
import org.openrewrite.text.PlainTextVisitor


class KotlinReplaceAllRecipe @JsonCreator constructor(
  @Option(
    displayName = "Replacement Text",
    description = "Resulting text after the replacement occurs."
  ) @JsonProperty("replacementText") val replacementText: String
): Recipe() {
  override fun getDisplayName() = "Tests a simple Kotlin Recipe With Options"
  override fun getDescription() = "A test case for recipe authoring in Kotlin."

  override fun getVisitor(): TreeVisitor<*, ExecutionContext> =
    object: PlainTextVisitor<ExecutionContext>() {
      override fun visitText(text: PlainText, p: ExecutionContext): PlainText {
        return super.visitText(text.withText(replacementText), p)
      }
    }
}
```
### Recipe Test
```kotlin
package net.sample.kotlin

import org.junit.jupiter.api.Test
import org.openrewrite.test.RecipeSpec
import org.openrewrite.test.RewriteTest
import org.openrewrite.test.SourceSpecs.text

class KotlinReplaceAllRecipeTest: RewriteTest {
  override fun defaults(spec: RecipeSpec) {
    spec.recipeFromResources("net.sample.kotlin.KotlinReplaceAllRecipeWrapper")
  }

  @Test
  fun `replaces all text with provided replacement argument text`() = rewriteRun(text("Some Text", "REPLACEMENT_TEXT"))
}
```
### Test Output
```txt
Expected :"REPLACEMENT_TEXT"
Actual   :""
```

## What did you expect to see?
"REPLACEMENT_TEXT"

## What did you see instead?
""
