### ISSUE TITLE
TypecastParenPad not working properly in some cases

### ISSUE THREAD

**Issue by mhagnumdw** [openrewrite/rewrite#5669]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.55.0
- Maven/Gradle plugin v6.11.0
- rewrite-static-analysis v2.10.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
    <groupId>org.openrewrite.maven</groupId>
    <artifactId>rewrite-maven-plugin</artifactId>
    <version>6.11.0</version>
    <configuration>
        <exportDatatables>true</exportDatatables>
        <activeRecipes>
            <recipe>org.mhagnumdw.MhagnumDwCodeQuality</recipe>
        </activeRecipes>
        <failOnDryRunResults>true</failOnDryRunResults>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-rewrite</artifactId>
            <version>0.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-static-analysis</artifactId>
            <version>2.10.0</version>
        </dependency>
    </dependencies>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
public class FormatSqlFileVisitor extends TreeVisitor<Tree, ExecutionContext> {
    @Override
    public @Nullable SourceFile visit(@Nullable Tree tree, ExecutionContext p) {
        return (SourceFile) Objects.requireNonNull(tree);
    }
}
```

## What did you expect to see?

```java
public class FormatSqlFileVisitor extends TreeVisitor<Tree, ExecutionContext> {
    @Override
    public @Nullable SourceFile visit(@Nullable Tree tree, ExecutionContext p) {
        return (SourceFile) Objects.requireNonNull(tree);
    }
}
```

## What did you see instead?

```java
public class FormatSqlFileVisitor extends TreeVisitor<Tree, ExecutionContext> {
    @Override
    public @Nullable SourceFile visit(@Nullable Tree tree, ExecutionContext p) {
        return (SourceFile) Objects.requireNonNull( tree );
    }
}
```

⚠️ Note the space before and after the `tree`.

## What is the full stack trace of any errors you encountered?

```
[WARNING] Changes have been made to src/main/java/io/github/mhagnumdw/FormatSqlFileVisitor.java by:
[WARNING]     org.openrewrite.staticanalysis.CustomCodeCleanup1
[WARNING]         org.openrewrite.staticanalysis.TypecastParenPad
[WARNING] Please review and commit the results.
[WARNING] Estimate time saved: 5m
```

## My `rewrite.yml`
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.staticanalysis.CustomCodeCleanup1
displayName: Code cleanup (custom)
description: Automatically cleanup code, e.g. remove unnecessary parentheses,
  simplify expressions.
recipeList:
  - org.openrewrite.staticanalysis.DefaultComesLast
  - org.openrewrite.staticanalysis.EmptyBlock
  - org.openrewrite.java.format.EmptyNewlineAtEndOfFile
  - org.openrewrite.staticanalysis.ForLoopControlVariablePostfixOperators
  - org.openrewrite.staticanalysis.FinalizePrivateFields
  - org.openrewrite.java.format.PadEmptyForLoopComponents
  - org.openrewrite.staticanalysis.TypecastParenPad
  - org.openrewrite.staticanalysis.EqualsAvoidsNull
  - org.openrewrite.staticanalysis.ExplicitInitialization
  - org.openrewrite.staticanalysis.FallThrough
  - org.openrewrite.staticanalysis.HideUtilityClassConstructor
  - org.openrewrite.staticanalysis.NeedBraces
  - org.openrewrite.staticanalysis.OperatorWrap
  - org.openrewrite.staticanalysis.UnnecessaryParentheses
  - org.openrewrite.staticanalysis.ReplaceThreadRunWithThreadStart
  - org.openrewrite.staticanalysis.ChainStringBuilderAppendCalls
  - org.openrewrite.staticanalysis.ReplaceStringBuilderWithString
  - org.openrewrite.java.ShortenFullyQualifiedTypeReferences
  - org.openrewrite.staticanalysis.CustomImportOrder
---
type: specs.openrewrite.org/v1beta/recipe
name: org.mhagnumdw.MhagnumDwCodeQuality
displayName: MhagnumDwCodeQuality
description: ""
recipeList:
  - org.openrewrite.maven.RemoveUnusedProperties
  - org.openrewrite.maven.BestPractices
  - org.openrewrite.java.format.RemoveTrailingWhitespace
  - org.openrewrite.java.recipes.RecipeNullabilityBestPractices
  - org.openrewrite.java.recipes.JavaRecipeBestPractices
  - org.openrewrite.staticanalysis.CustomCodeCleanup1
  - org.openrewrite.staticanalysis.CommonStaticAnalysis
  - org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices
```

**Comment by timtebeek** [comment]
Hi! That recipe takes either an implicit detected style, or an explicit provided Style, as detailed on: https://docs.openrewrite.org/concepts-and-explanations/styles
From what you've shared it seems you're not passing in any explicit style; so then the detection looks at what's most common across your project and standardizes on that. Could it be that you're mostly using the style with spaces between the parentheses currently, but want to switch to the alternate style without spaces? In that case you might want to configure an explicit style when your run that recipe.

**Comment by mhagnumdw** [comment]
Hi! I haven’t configured any specific style. My code doesn’t use spaces inside parentheses. I’m not sure why the TypecastParenPad recipe is assuming I do.

All my code follows the style `Objects.requireNonNull(tree);` not `Objects.requireNonNull( tree );`. I want it without spaces.

I tried creating a minimal reproducible example, but the spaces weren’t added. In my actual code, after removing a few classes, the spaces stopped being added as well.

I also tried explicitly setting the following style, and spaces were added:
```yaml
styleConfigs:
  - org.openrewrite.java.style.TypecastParenPadStyle:
      space: false
```

I also tried using the `org.openrewrite.java.style.IntelliJ` style.

I can share the real code later so we have a proper example. Feel free to close this issue for now - I can reopen it later if needed. Thanks @timtebeek !
