### ISSUE TITLE
ChangeMethodName does not update declaringType.name when the declaring type matches the method matcher

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#605]
The `JunitMockitoUpgradeIntegrationTest.replacesAnyVararg` test exposes an issue where a series of declarative recipes used for converting types and names are not updating the methodInvocations `declaringType.name`.  This results in a bug where `RemoveImport` removes the `mockito.ArgumentMatchers.any` import because its associated type is not found in the `TypeCache.`

```yaml
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.mockito.MockitoAnnotations.Mock
      newFullyQualifiedTypeName: org.mockito.Mock
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Matchers anyVararg()
      newMethodName: any
```
![image](https://user-images.githubusercontent.com/22326988/120407766-a75a5c80-c302-11eb-9c28-248017cdb7a9.png)
