### ISSUE TITLE
New "category" resource to describe what packages of recipes do

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#625]
...and give them a name. For example:

```yaml
---
type: specs.openrewrite.org/v1beta/category
name: Java
packageName: org.openrewrite.java
description: Basic building blocks for transforming Java code.
```
