### ISSUE TITLE
Maven change property value or upgrade version changes un-related property values

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#891]
```yaml
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: io.micronaut
      artifactId: micronaut-bom
      newVersion: 3.0.0-M5
      trustParent: true
  - org.openrewrite.maven.ChangePropertyValue:
      key: micronaut.version
      newValue: 3.0.0-M5
```

![image](https://user-images.githubusercontent.com/22326988/129244842-41bf1689-5f33-4b3b-9745-1cefd7a42452.png)

# AG edits below: 

Possibly similar: https://github.com/openrewrite/rewrite/issues/739

`ChangePropertyValue` appears to have the desired change effect. Believe this problem is rooted in `UpgradeDependencyVersion`
